/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HeartRhythmUI.framework/HeartRhythmUI
 */

@interface HROnboardingAtrialFibrillationWhatIsViewController : HROnboardingHeroExplanationViewController {
    HRVideoPlayerView * _videoPlayerView;
}

@property (nonatomic, retain) HRVideoPlayerView *videoPlayerView;

- (void).cxx_destruct;
- (id)bodyString;
- (id)buttonTitleString;
- (id)createHeroView;
- (id)initForOnboarding:(bool)arg1 upgradingFromAlgorithmVersion:(long long)arg2;
- (void)setUpUI;
- (void)setVideoPlayerView:(id)arg1;
- (long long)stackedButtonViewLastButtonMode;
- (id)titleString;
- (id)videoPlayerView;
- (void)viewDidDisappear:(bool)arg1;
- (void)viewWillAppear:(bool)arg1;

@end
