//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AVFoundation/NSObject-Protocol.h>

@class AVOutputDevice, NSString;

@protocol AVOutputDeviceAuthorizationRequestImpl <NSObject>
@property(readonly, nonatomic) NSString *authorizationTokenType;
@property(readonly, nonatomic) AVOutputDevice *outputDevice;
@property(readonly, nonatomic) NSString *ID;
- (void)cancel;
- (void)respondWithAuthorizationToken:(NSString *)arg1 completionHandler:(void (^)(long long, NSError *))arg2;
@end

