//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVFigPlaylistNodeConvertible.h"
#import "AVPlaylistNode.h"

@class AVPlaylistInternal, NSArray, NSString;

@interface AVPlaylist : NSObject <AVFigPlaylistNodeConvertible, AVPlaylistNode>
{
    AVPlaylistInternal *_ivars;
}

+ (void)initialize;
- (void)applyPendingChangesWithCompletionHandler:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) BOOL appliesChangesImmediately;
@property(readonly, nonatomic) __weak AVPlaylist *parentPlaylist;
- (void)removeAllNodes;
- (void)removeNode:(id)arg1;
- (void)insertNode:(id)arg1 afterNode:(id)arg2;
- (void)appendNode:(id)arg1;
- (void)fetchPlaylistForIdentifier:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)fetchPlaylistNodeForIdentifier:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)setActionAtEnd:(long long)arg1;
- (long long)actionAtEnd;
@property(readonly, nonatomic, getter=_figPlaylist) struct OpaqueFigPlaylist *figPlaylist;
@property(readonly, nonatomic) CDStruct_2bd8379f *figPlaylistNode;
@property(copy, nonatomic) NSArray *metadata;
@property(readonly, nonatomic) id <NSObject><NSCopying><NSSecureCoding> identifier;
@property(readonly) unsigned long long hash;
- (BOOL)isEqual:(id)arg1;
@property(readonly, copy) NSString *description;
- (void)finalize;
- (void)dealloc;
- (id)initWithFigPlaylist:(struct OpaqueFigPlaylist *)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

