//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface HelpSDMIndexFile : NSObject
{
}

+ (BOOL)createSDMIndexFileFromHelpBookBundle:(id)arg1 forLanguage:(id)arg2 atSDMModelPath:(id)arg3;
+ (id)helpIndexFilePathInBundle:(id)arg1 forLanguage:(id)arg2;
+ (id)loadIndexFromIndexFile:(id)arg1;
+ (id)loadIndexForHelpBook:(id)arg1 fromSDMModelPath:(id)arg2;
+ (BOOL)createSDMIndexFileFromHelpIndexFile:(id)arg1 bookIdentifier:(id)arg2 atSDMModelPath:(id)arg3 language:(id)arg4;

@end

