/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/FamilyCircle.framework/FamilyCircle
 */

@interface FABroadcaster : NSObject

+ (void)_broadcastNotificationName:(id)arg1 userInfo:(id)arg2;
+ (void)broadcastFamilyChangedNotification;
+ (void)broadcastRemoteUIWillDismissNotification:(id)arg1;
+ (void)broadcastServicesChangedNotification;

@end
