/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Translation.framework/Translation
 */

@interface FTMutableRecognitionPhraseTokens : FTRecognitionPhraseTokens

@property (nonatomic, copy) NSArray *tokens;

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)init;
- (void)setTokens:(id)arg1;
- (id)tokens;

@end
