//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface CSiTunesAccountManager : NSObject
{
}

+ (id)addiTunesAccountWithMultiUserToken:(id)arg1 withDsid:(id)arg2 withAltDsid:(id)arg3 withHomeId:(id)arg4 withHomeUserId:(id)arg5 forProfileId:(id)arg6;

@end

