//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CalendarPersistence/CoreDAVLocalDBInfoProvider-Protocol.h>

@class CoreDAVItemParserMapping, NSDictionary, NSString, NSURL;

@protocol CalDAVChecksumLocalDBInfoProvider <CoreDAVLocalDBInfoProvider>
- (void)reportMismatchedChecksum:(NSString *)arg1 forURL:(NSURL *)arg2 inFolderWithURL:(NSURL *)arg3 checksumVersion:(CoreDAVItemParserMapping *)arg4 eTag:(NSString *)arg5;
- (void)reportMismatchedETag:(NSString *)arg1 forURL:(NSURL *)arg2 inFolderWithURL:(NSURL *)arg3 cTag:(NSString *)arg4 syncToken:(NSString *)arg5 eTag:(NSString *)arg6 mismatchType:(int)arg7;
- (NSDictionary *)copyLocalChecksumsForFolderWithURL:(NSURL *)arg1 checksumVersion:(CoreDAVItemParserMapping *)arg2;
@end

