//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class NSArray;

@interface CalTruthFileOperation : NSOperation
{
    NSArray *_methods;
    BOOL _disabledSuddenTermination;
}

+ (id)operationWithMethods:(id)arg1;
- (void).cxx_destruct;
- (void)main;
- (void)finalize;
- (void)dealloc;
- (void)_enableSuddenTerminationIfNeeded;
- (id)initWithMethods:(id)arg1;

@end

