//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface CALWeekDayNumber : NSObject
{
    long long _number;
    unsigned long long _day;
}

+ (id)weekDayNumberWithDay:(unsigned long long)arg1 withNumber:(long long)arg2;
- (long long)compareDay:(id)arg1;
- (id)description;
- (id)setNumber:(long long)arg1;
- (long long)number;
- (id)setDay:(unsigned long long)arg1;
- (unsigned long long)day;
- (BOOL)isEqual:(id)arg1;
- (id)initWithDay:(unsigned long long)arg1 withNumber:(long long)arg2;

@end

