/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeAutomationInternal.framework/HomeAutomationInternal
 */

@interface HomeAutomationInternal.MutableControlHomeIntentResponse : _TtCs12_SwiftObject {
    void code;
    void entityResponses;
}

@end
