//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PhotosPlayer/ISSettings.h>

@interface ISPlayerSettings : ISSettings
{
    BOOL _useDedicatedQueues;
    BOOL _allowFrameBlending;
    BOOL _allowVideoPreRoll;
    BOOL _allowPlayerReuse;
    BOOL _allowCrossfadeContent;
    BOOL _shouldPauseOnSettle;
    BOOL _variableIntro;
    BOOL _assumeCroppedVideo;
    double _forceTouchTimeoutInterval;
    double _forceTouchTimeoutMinimumProgress;
    double _forceScrubMinimumPressure;
    double _forceScrubMaximumPressure;
    double _forceScrubRewindFactor;
    double _forceScrubMinRateChange;
    double _forceScrubSettleRateAddition;
    double _forceScrubMinimumRate;
    double _forceScrubMaximumInteractiveRate;
    double _audioRampDuration;
    double _crossfadeTargetBlur;
    double _crossfadeDuration;
    double _maxPreCrossfadeDuration;
    double _nonForcePreCrossfadeDuration;
}

+ (id)sharedInstance;
@property(nonatomic) BOOL assumeCroppedVideo; // @synthesize assumeCroppedVideo=_assumeCroppedVideo;
@property(nonatomic) BOOL variableIntro; // @synthesize variableIntro=_variableIntro;
@property(nonatomic) double nonForcePreCrossfadeDuration; // @synthesize nonForcePreCrossfadeDuration=_nonForcePreCrossfadeDuration;
@property(nonatomic) double maxPreCrossfadeDuration; // @synthesize maxPreCrossfadeDuration=_maxPreCrossfadeDuration;
@property(nonatomic) double crossfadeDuration; // @synthesize crossfadeDuration=_crossfadeDuration;
@property(nonatomic) double crossfadeTargetBlur; // @synthesize crossfadeTargetBlur=_crossfadeTargetBlur;
@property(nonatomic) double audioRampDuration; // @synthesize audioRampDuration=_audioRampDuration;
@property(nonatomic) double forceScrubMaximumInteractiveRate; // @synthesize forceScrubMaximumInteractiveRate=_forceScrubMaximumInteractiveRate;
@property(nonatomic) double forceScrubMinimumRate; // @synthesize forceScrubMinimumRate=_forceScrubMinimumRate;
@property(nonatomic) double forceScrubSettleRateAddition; // @synthesize forceScrubSettleRateAddition=_forceScrubSettleRateAddition;
@property(nonatomic) double forceScrubMinRateChange; // @synthesize forceScrubMinRateChange=_forceScrubMinRateChange;
@property(nonatomic) double forceScrubRewindFactor; // @synthesize forceScrubRewindFactor=_forceScrubRewindFactor;
@property(nonatomic) double forceScrubMaximumPressure; // @synthesize forceScrubMaximumPressure=_forceScrubMaximumPressure;
@property(nonatomic) double forceScrubMinimumPressure; // @synthesize forceScrubMinimumPressure=_forceScrubMinimumPressure;
@property(nonatomic) double forceTouchTimeoutMinimumProgress; // @synthesize forceTouchTimeoutMinimumProgress=_forceTouchTimeoutMinimumProgress;
@property(nonatomic) double forceTouchTimeoutInterval; // @synthesize forceTouchTimeoutInterval=_forceTouchTimeoutInterval;
@property(nonatomic) BOOL shouldPauseOnSettle; // @synthesize shouldPauseOnSettle=_shouldPauseOnSettle;
@property(nonatomic) BOOL allowCrossfadeContent; // @synthesize allowCrossfadeContent=_allowCrossfadeContent;
@property(nonatomic) BOOL allowPlayerReuse; // @synthesize allowPlayerReuse=_allowPlayerReuse;
@property(nonatomic) BOOL allowVideoPreRoll; // @synthesize allowVideoPreRoll=_allowVideoPreRoll;
@property(nonatomic) BOOL allowFrameBlending; // @synthesize allowFrameBlending=_allowFrameBlending;
@property(nonatomic) BOOL useDedicatedQueues; // @synthesize useDedicatedQueues=_useDedicatedQueues;
- (void)setDefaultValues;

@end

