//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVPlayerItem, ISWrappedAVPlayer;

@protocol ISWrappedAVPlayerDelegate <NSObject>
- (void)avPlayer:(ISWrappedAVPlayer *)arg1 item:(AVPlayerItem *)arg2 didChangeToStatus:(long long)arg3;
- (void)avPlayer:(ISWrappedAVPlayer *)arg1 didChangeToItem:(AVPlayerItem *)arg2;
- (void)avPlayer:(ISWrappedAVPlayer *)arg1 didChangeToStatus:(long long)arg2;
@end

