/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreKit.framework/AppStoreKit
 */

@interface AppStoreKit.ClientOrdering : _TtCs12_SwiftObject {
    void inAppProvider;
}

@end
