/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI
 */

@interface HKUIMetricColors : NSObject {
    UIColor * _contextViewInfoButtonBackgroundColor;
    UIColor * _contextViewInfoButtonGlyphColor;
    UIColor * _contextViewPrimaryTextColor;
    UIColor * _contextViewSecondaryTextColor;
    UIColor * _keyColor;
}

@property (nonatomic, retain) UIColor *contextViewInfoButtonBackgroundColor;
@property (nonatomic, retain) UIColor *contextViewInfoButtonGlyphColor;
@property (nonatomic, retain) UIColor *contextViewPrimaryTextColor;
@property (nonatomic, retain) UIColor *contextViewSecondaryTextColor;
@property (nonatomic, retain) UIColor *keyColor;

// Image: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI

+ (id)activityColors;
+ (id)allergiesClinicalColors;
+ (id)bodyMeasurementColors;
+ (id)carePlansClinicalColors;
+ (id)conditionsClinicalColors;
+ (id)defaultClinicalColors;
+ (id)defaultContextViewColorsUsingColor:(id)arg1;
+ (id)devicesClinicalColors;
+ (id)hearingHealthColors;
+ (id)immunizationsClinicalColors;
+ (id)insuranceClinicalColors;
+ (id)labResultsClinicalColors;
+ (id)medicationsClinicalColors;
+ (id)metricColorsForHeartRateContext:(long long)arg1;
+ (id)mindfulnessColors;
+ (id)mobilityColors;
+ (id)otherColors;
+ (id)proceduresClinicalColors;
+ (id)reproductiveHealthColors;
+ (id)respiratoryColors;
+ (id)sleepColors;
+ (id)socialHistoryClinicalColors;
+ (id)symptomsColors;
+ (id)unknownCategoryClinicalColors;
+ (id)vitalsClinicalColors;
+ (id)vitalsColors;
+ (id)workoutContextViewColors;

- (void).cxx_destruct;
- (id)contextViewInfoButtonBackgroundColor;
- (id)contextViewInfoButtonGlyphColor;
- (id)contextViewPrimaryTextColor;
- (id)contextViewSecondaryTextColor;
- (id)keyColor;
- (void)setContextViewInfoButtonBackgroundColor:(id)arg1;
- (void)setContextViewInfoButtonGlyphColor:(id)arg1;
- (void)setContextViewPrimaryTextColor:(id)arg1;
- (void)setContextViewSecondaryTextColor:(id)arg1;
- (void)setKeyColor:(id)arg1;

// Image: /System/Library/PrivateFrameworks/HealthRecordsUI.framework/HealthRecordsUI

+ (id)chartFilterDefaultForMultiple;
+ (id)chartFilterDefaultForSingle;

@end
