//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WiFiPolicy/NSCopying-Protocol.h>
#import <WiFiPolicy/NSObject-Protocol.h>

@class NSArray, NSDictionary;
@protocol TBFetchRequestDescriptor, TBFetchResponse;

@protocol TBFetchRequest <NSObject, NSCopying>
@property(readonly, nonatomic) BOOL cacheable;
@property(copy, nonatomic) CDUnknownBlockType preferLocalHandler;
@property(copy, nonatomic) CDUnknownBlockType resultsHandler;
@property(nonatomic) unsigned long long sourcePolicy;
@property(readonly, nonatomic) id <TBFetchRequestDescriptor> descriptor;
- (void)handleResponse:(id <TBFetchResponse>)arg1;

@optional
@property(retain, nonatomic) NSDictionary *userInfo;
- (void)handlePreferLocalResponse:(NSArray *)arg1;
@end

