//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WiFiPolicy/WFLoggerBase.h>

@class NSDateFormatter, NSObject;
@protocol OS_dispatch_queue;

@interface WFLoggerCircularBuffer : WFLoggerBase
{
    char *_wiFiLoggingLogBufferRef;
    long long _wiFiLoggingLogBufferIndex;
    long long _wiFiLoggingLogBufferMaxSize;
    unsigned int _dumpId;
    NSDateFormatter *_tsFormatter;
    NSObject<OS_dispatch_queue> *_dispatchQueue;
}

- (void)dump;
- (id)init;
- (void)dealloc;
- (void)WFLog:(unsigned long long)arg1 privacy:(unsigned long long)arg2 cfStrMsg:(struct __CFString *)arg3;
- (void)WFLog:(unsigned long long)arg1 privacy:(unsigned long long)arg2 message:(const char *)arg3 valist:(struct __va_list_tag [1])arg4;

@end

