//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface NUGeometryTransform : NSObject
{
}

- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)description;
- (CDStruct_14d5dc5e)transformMatrix:(CDStruct_14d5dc5e)arg1;
- (CDStruct_1b6d18a9)transformTime:(CDStruct_1b6d18a9)arg1;
- (struct CGPoint)transformPoint:(struct CGPoint)arg1;
- (id)inverseTransform;

@end

