//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <NeutrinoCore/NUJSRational.h>

@class NSValue;

@interface NUJSTime : NUJSRational
{
}

- (id)nu_unwrapJSValue;
@property(readonly) NSValue *value;
@property(readonly) CDStruct_1b6d18a9 time;
- (id)initWithTime:(CDStruct_1b6d18a9)arg1;

@end

