/* Generated by RuntimeBrowser
   Image: /usr/lib/swift/libswiftNetwork.dylib
 */

@interface Network.NWMulticastGroup : _TtCs12_SwiftObject {
    void groupAddresses;
    void isUnicastDisabled;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  sourceFilter;
}

@end
