//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mondrian/NSObject-Protocol.h>

@class MOMediaSection, NSDate, NSString;

@protocol MOMediaSectionFormattingDelegate <NSObject>
- (NSString *)mediaSection:(MOMediaSection *)arg1 stringForRangeFromDate:(NSDate *)arg2 toDate:(NSDate *)arg3;
@end

