//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSProxy.h>

@class ISS_AYOperation;

@interface ISS__AYProxy : NSProxy
{
    ISS_AYOperation *_operation;
    BOOL _asyncLaunch;
}

- (id)description;
- (id)methodSignatureForSelector:(SEL)arg1;
- (void)forwardInvocation:(id)arg1;
- (BOOL)conformsToProtocol:(id)arg1;
- (BOOL)respondsToSelector:(SEL)arg1;
- (void)setAsyncLaunch:(BOOL)arg1;
- (id)initWithOperation:(id)arg1;

@end

