/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VideoProcessing.framework/VideoProcessing
 */

@interface VCPFaceCropGenerator : NSObject

+ (id)_faceCropDataForImage:(id)arg1 andNormalizedFaceRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg2 error:(id*)arg3;
+ (id)_generateFaceCropWithDescriptor:(id)arg1 andCancelBlock:(id)arg2 error:(id*)arg3;
+ (void)_reportCancellationOfRemainingFaceCropSourceDescriptors:(id)arg1 withStartingIndex:(unsigned long long)arg2 andFailureBlock:(id /* block */)arg3;
+ (id)generateFaceCropsFromSourceDescriptors:(id)arg1 withProgressBlock:(id /* block */)arg2 andFailureBlock:(id /* block */)arg3 andCancelBlock:(id)arg4;

@end
