/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MessageProtection.framework/MessageProtection
 */

@interface SecKeyP256Public : NSObject <P256PublicKeyProtocol> {
    struct __SecKey { } * _publicKeyRef;
    NSData * _serializedKey;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property struct __SecKey { }*publicKeyRef;
@property (retain) NSData *serializedKey;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)dataRepresentation;
- (void)dealloc;
- (id)initWithData:(id)arg1 error:(id*)arg2;
- (id)initWithSecKeyRef:(struct __SecKey { }*)arg1;
- (struct __SecKey { }*)publicKeyRef;
- (id)serializedKey;
- (void)setPublicKeyRef:(struct __SecKey { }*)arg1;
- (void)setSerializedKey:(id)arg1;
- (bool)verifySignature:(id)arg1 data:(id)arg2;

@end
