//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Notes/ICNFIMAPFetchResult.h>

@interface ICNFIMAPUidFetchResult : ICNFIMAPFetchResult
{
    unsigned int _uid;
}

@property(nonatomic) unsigned int uid; // @synthesize uid=_uid;
- (id)description;

@end

