//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CKCoalescer;

@protocol CKCoalescerDelegate <NSObject>
- (void)coalescerDidCancel:(CKCoalescer *)arg1;
- (void)coalescerDidPause:(CKCoalescer *)arg1;
- (void)coalescerDidResume:(CKCoalescer *)arg1;
@end

