//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <NeutrinoCore/NUAutoCalculator.h>

@interface PIRedEyeAutoCalculator : NUAutoCalculator
{
    BOOL _force;
}

@property BOOL force; // @synthesize force=_force;
- (void)submit:(CDUnknownBlockType)arg1;
- (void)_configureRequest:(id)arg1;
- (id)_options;

@end

