/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Announce.framework/Announce
 */

@interface ANAnnouncementStatePublisher : NSObject {
    char * _name;
    NSObject<OS_dispatch_queue> * _queue;
    int  _registrationToken;
}

- (void).cxx_destruct;
- (void)_register;
- (bool)_setState:(unsigned long long)arg1 withToken:(int)arg2;
- (void)_unregister;
- (void)dealloc;
- (id)initWithName:(id)arg1 queue:(id)arg2;
- (void)invalidate;
- (void)publishAnnouncePlaybackState:(unsigned long long)arg1;

@end
