//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MDSMachPortNotificationRecord : NSObject
{
    unsigned int _previousPort;
    SEL _aSelector;
    id _anObject;
}

- (id)object;
- (SEL)selector;
- (unsigned int)previousPort;
- (void)dealloc;
- (id)initWithPreviousPort:(unsigned int)arg1 selector:(SEL)arg2 andObject:(id)arg3;

@end

