/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriSettingsIntents.framework/SiriSettingsIntents
 */

@interface _TtCC19SiriSettingsIntents28SettingsNumericSettingAction7Builder : _TtCs12_SwiftObject {
    void isDecrease;
    void isIncrease;
    void isMaximum;
    void isMinimum;
    void isSetValue;
    void value;
}

@end
