/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriSettingsIntents.framework/SiriSettingsIntents
 */

@interface SiriSettingsIntents.SetLabeledIntentHandler : NSObject <INSetLabeledSettingIntentHandling>

- (void)handleSetLabeledSetting:(id)arg1 completion:(id /* block */)arg2;
- (id)init;

@end
