/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SleepDaemon.framework/SleepDaemon
 */

@interface HDSPSleepLockScreenStateMachineState : HKSPPersistentStateMachineState <HDSPSleepLockScreenStateMachineEventHandler>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) HDSPSleepLockScreenStateMachine *stateMachine;
@property (readonly) Class superclass;

- (void)_updateStateForSleepMode:(long long)arg1 reason:(unsigned long long)arg2 context:(id)arg3;
- (void)didEnterWithPreviousState:(id)arg1 context:(id)arg2;
- (void)dismissAlertForGoodMorning;
- (void)environmentDidBecomeReady;
- (bool)isSleepLockScreenDisabled;
- (void)presentAlertForGoodMorning;
- (long long)sleepLockScreenState;
- (void)sleepModeDidChange:(long long)arg1 reason:(unsigned long long)arg2;
- (void)updateState;

@end
