//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Safari/TextFieldWithVibrancy.h>

__attribute__((visibility("hidden")))
@interface AccessibleGroupedTextFieldWithVibrancy : TextFieldWithVibrancy
{
    BOOL _primaryElement;
    long long _siblingGroupingId;
}

@property(nonatomic, getter=isPrimaryElement) BOOL primaryElement; // @synthesize primaryElement=_primaryElement;
@property(nonatomic) long long siblingGroupingId; // @synthesize siblingGroupingId=_siblingGroupingId;
- (id)accessibilityRole;
- (id)accessibilityChildren;
- (struct CGRect)accessibilityFrame;
- (id)accessibilityValue;
- (BOOL)isAccessibilityElement;

@end

