//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <Safari/NSTouchBarDelegate-Protocol.h>
#import <Safari/NSTouchBarProvider-Protocol.h>

@class NSButton, NSString, NSTouchBar;
@protocol AppControllerTouchBarProviderDelegate;

__attribute__((visibility("hidden")))
@interface AppControllerTouchBarProvider : NSObject <NSTouchBarDelegate, NSTouchBarProvider>
{
    NSTouchBar *_touchBar;
    id <AppControllerTouchBarProviderDelegate> _delegate;
    NSButton *_newWindowButton;
    NSButton *_newPrivateBrowsingWindowButton;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <AppControllerTouchBarProviderDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_openNewPrivateBrowsingWindow:(id)arg1;
- (void)_openNewWindow:(id)arg1;
@property(readonly, nonatomic) NSButton *newPrivateBrowsingWindowButton; // @synthesize newPrivateBrowsingWindowButton=_newPrivateBrowsingWindowButton;
@property(readonly, nonatomic) NSButton *newWindowButton; // @synthesize newWindowButton=_newWindowButton;
- (id)touchBar:(id)arg1 makeItemForIdentifier:(id)arg2;
@property(readonly) NSTouchBar *touchBar;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

