//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <Safari/AuthenticationSessionNavigationHandling-Protocol.h>

@class ASWebAuthenticationSessionRequest, BrowserDocument;

__attribute__((visibility("hidden")))
@interface AuthenticationSession : NSObject <AuthenticationSessionNavigationHandling>
{
    BrowserDocument *_document;
    ASWebAuthenticationSessionRequest *_request;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) ASWebAuthenticationSessionRequest *request; // @synthesize request=_request;
- (void)_windowWillClose:(id)arg1;
- (void)_tearDown;
- (void)_unregisterForWindowCloseNotification;
- (void)_registerForWindowCloseNotification;
- (BOOL)handleNavigationToURL:(id)arg1;
- (void)cancel;
- (void)start;
- (id)initWithRequest:(id)arg1;

@end

