//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface BookmarkMoveUndoInfo : NSObject
{
    NSString *_parentUUID;
    unsigned long long _midMoveInitialIndex;
    NSMutableArray *_midMoveSourceBookmarkLocations;
}

- (void).cxx_destruct;
@property(readonly) unsigned long long midMoveInitialIndex; // @synthesize midMoveInitialIndex=_midMoveInitialIndex;
@property(readonly) NSString *parentUUID; // @synthesize parentUUID=_parentUUID;
- (id)midMoveSourceBookmarkLocations;
- (void)addMidMoveSourceBookmarkLocation:(id)arg1;
- (id)initWithParentUUID:(id)arg1 midMoveInitialIndex:(unsigned long long)arg2;
- (id)init;

@end

