//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Safari/ChromeImportEngine.h>

#import <Safari/BrowserCredentialImportEngine-Protocol.h>

@class NSString;
@protocol BrowserCredentialImporterDelegate;

__attribute__((visibility("hidden")))
@interface ChromeCredentialImportEngine : ChromeImportEngine <BrowserCredentialImportEngine>
{
    NSString *_safeStorageKey;
    BOOL _shouldSendImporterRequiresMasterPassword;
    id <BrowserCredentialImporterDelegate> _delegate;
}

- (void).cxx_destruct;
- (id)_encryptedCredentials;
- (id)_encryptedCredentialsWithLoginDatabaseURL:(id)arg1;
- (void)_importCredentials;
- (void)retryCredentialImport;
- (void)cancelCredentialImport;
- (void)importCredentialsWithDelegate:(id)arg1;
- (void)setShouldSendImporterRequiresMasterPassword:(BOOL)arg1;
- (void)setMasterPassword:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

