//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface PasswordsViewItem : NSObject
{
    NSString *_username;
    NSString *_domain;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *domain; // @synthesize domain=_domain;
@property(readonly, copy, nonatomic) NSString *username; // @synthesize username=_username;
- (id)initWithDomain:(id)arg1 username:(id)arg2;

@end

