//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class ABAddressBook, NSMutableString;

@interface ABAddressBookSummaryBuilder : NSObject
{
    ABAddressBook *_addressBook;
    NSMutableString *_summary;
}

- (id)_groupsInOrder;
- (void)_summarizeGroups;
- (id)_peopleInOrder;
- (void)_summarizePeople;
- (void)_addSummaryHeader;
- (void)_summarizeRecords:(id)arg1 withBuilder:(id)arg2;
- (void)_summarizeRecord:(id)arg1 withBuilder:(id)arg2;
- (void)_prepareRepresentation;
- (id)buildSummary;
- (void)dealloc;
- (id)initWithAddressBook:(id)arg1;

@end

