//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface ABImageLoadingTasks : NSObject
{
}

+ (id)gravatarImageLoaderTaskWithRequest:(id)arg1;
+ (id)directoryServicesImageTaskWithRequest:(id)arg1;
+ (id)libraryDirectoryImageTaskWithRequest:(id)arg1;
+ (id)remoteImageTaskWithRequest:(id)arg1;
+ (id)localLargeImageTaskWithRequest:(id)arg1;
+ (id)localThumbnailImageTaskWithRequest:(id)arg1;
+ (id)imageLoadingTaskForPerson:(id)arg1 emails:(id)arg2;
+ (id)imageTaskWithRequest:(id)arg1;

@end

