//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Accounts/ACAccount.h>

@class NSDictionary, NSString;

@interface ACAccount (CloudKitAdditions)
@property(readonly) NSString *ck_personaIdentifier;
@property(readonly) NSDictionary *ck_dataclassProperties;
@property(readonly) NSDictionary *ck_accountProperties;
@property(readonly) NSString *ck_identifier;
@property(readonly, nonatomic) ACAccount *ck_cloudKitAccount;
@end

