//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface ISyncRecordGraphNode : NSObject
{
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
- (id)orderedSubentityIdsFromIds:(id)arg1 usingEntityNames:(id)arg2 isAdd:(BOOL)arg3;
- (id)orderedSubentityIdsFromIds:(id)arg1 usingEntityNames:(id)arg2 defaultOrder:(id)arg3;
- (id)orderedSubentityIdsFromIds:(id)arg1 usingEntityNames:(id)arg2;
- (void)setChangedKeys:(id)arg1;
- (void)setDisplayKeys:(id)arg1;
- (void)setChangeType:(int)arg1;
- (id)initWithRecordView:(id)arg1 recordIdentifier:(id)arg2;
- (id)parentNode;
- (id)topLevelParentNode;
- (id)childNodesByRecordIdentifier;
- (id)deletedChildNodesByRelationship;
- (id)modifiedChildNodesByRelationship;
- (id)addedChildNodesByRelationship;
- (int)changeType;
- (id)changedKeys;
- (id)displayKeys;
- (id)dependenciesForPropertyName:(id)arg1;
- (id)identityKeys;
- (id)relationshipNames;
- (id)entityName;
- (id)recordIdentifier;
- (id)record;
- (id)recordView;

@end

