/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthToolbox.framework/HealthToolbox
 */

@interface WDAppSourcesViewController : WDSourcesViewController

+ (id)tableViewSectionClasses;

- (id)initWithProfile:(id)arg1 usingInsetStyling:(bool)arg2;

@end
