//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UXKit/UXCollectionReusableView.h>

@class NSMutableArray, UXLabel, UXView;

@interface UXTableViewHeaderFooterView : UXCollectionReusableView
{
    NSMutableArray *_constraints;
    UXLabel *_textLabel;
    UXLabel *_detailTextLabel;
    UXView *_contentView;
    UXView *_backgroundView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UXView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) UXView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UXLabel *detailTextLabel; // @synthesize detailTextLabel=_detailTextLabel;
@property(retain, nonatomic) UXLabel *textLabel; // @synthesize textLabel=_textLabel;
- (void)prepareForReuse;
- (void)updateConstraints;
- (id)initWithReuseIdentifier:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

