//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CXCopying.h"
#import "NSCopying.h"
#import "NSSecureCoding.h"

@class NSArray, NSString, NSURL;

@interface CXProviderConfiguration : NSObject <NSSecureCoding, CXCopying, NSCopying>
{
    BOOL _supportsVideo;
    BOOL _supportsAudioOnly;
    BOOL _supportsEmergency;
    BOOL _supportsVoicemail;
    BOOL _hasRestrictionsInRetailEnvironment;
    unsigned int _audioSessionID;
    NSString *_localizedName;
    unsigned long long _maximumCallGroups;
    unsigned long long _maximumCallsPerCallGroup;
    NSArray *_emergencyNumbers;
    NSArray *_handoffIdentifiers;
    NSURL *_ringtoneSoundURL;
}

+ (BOOL)supportsSecureCoding;
@property(nonatomic) BOOL hasRestrictionsInRetailEnvironment; // @synthesize hasRestrictionsInRetailEnvironment=_hasRestrictionsInRetailEnvironment;
@property(nonatomic) BOOL supportsVoicemail; // @synthesize supportsVoicemail=_supportsVoicemail;
@property(nonatomic) BOOL supportsEmergency; // @synthesize supportsEmergency=_supportsEmergency;
@property(nonatomic) BOOL supportsAudioOnly; // @synthesize supportsAudioOnly=_supportsAudioOnly;
@property(copy, nonatomic) NSURL *ringtoneSoundURL; // @synthesize ringtoneSoundURL=_ringtoneSoundURL;
@property(copy, nonatomic) NSArray *handoffIdentifiers; // @synthesize handoffIdentifiers=_handoffIdentifiers;
@property(copy, nonatomic) NSArray *emergencyNumbers; // @synthesize emergencyNumbers=_emergencyNumbers;
@property(nonatomic) unsigned int audioSessionID; // @synthesize audioSessionID=_audioSessionID;
@property(nonatomic) BOOL supportsVideo; // @synthesize supportsVideo=_supportsVideo;
@property(nonatomic) unsigned long long maximumCallsPerCallGroup; // @synthesize maximumCallsPerCallGroup=_maximumCallsPerCallGroup;
@property(nonatomic) unsigned long long maximumCallGroups; // @synthesize maximumCallGroups=_maximumCallGroups;
@property(copy, nonatomic) NSString *localizedName; // @synthesize localizedName=_localizedName;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)updateCopy:(id)arg1 withZone:(struct _NSZone *)arg2;
- (id)sanitizedCopyWithZone:(struct _NSZone *)arg1;
- (id)sanitizedCopy;
- (void)updateSanitizedCopy:(id)arg1 withZone:(struct _NSZone *)arg2;
- (BOOL)supportsAudioAndVideo;
- (void)setSupportsAudioAndVideo:(BOOL)arg1;
@property(retain, nonatomic) NSString *ringtoneSound;
@property(readonly, copy) NSString *description;
- (id)initWithLocalizedName:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

