/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/LinkPresentation.framework/LinkPresentation
 */

@interface LPIndeterminateProgressSpinnerView : LPComponentView {
    UIView * _platformView;
}

- (void).cxx_destruct;
- (void)ensurePlatformView;
- (void)layoutComponentView;
- (struct CGSize { double x1; double x2; })sizeThatFits:(struct CGSize { double x1; double x2; })arg1;

@end
