/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
 */

@interface EKCalendarChooserTableHeaderView : UIView {
    UILabel * _label;
    double  _tableViewWidth;
}

@property (nonatomic, readonly) double tableViewWidth;

- (void).cxx_destruct;
- (id)initWithTextMode:(int)arg1;
- (void)setTableViewWidth:(double)arg1;
- (double)tableViewWidth;

@end
