/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VideosUI.framework/VideosUI
 */

@interface VideosUI.JSService : IKJSObject <VideosUI.JSServiceInterface>

- (id)init;
- (id)initWithAppContext:(id)arg1;

@end
