/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VideosUI.framework/VideosUI
 */

@interface VUIActiveInteractionView : NSObject {
    UIContextMenuInteraction * _activeInteraction;
    UIView * _highlightedView;
    <VUIContextMenuTemplateControllerInterface> * _templateInterface;
}

@property (nonatomic) UIContextMenuInteraction *activeInteraction;
@property (nonatomic) UIView *highlightedView;
@property (nonatomic) <VUIContextMenuTemplateControllerInterface> *templateInterface;

+ (id)sharedInstance;

- (void).cxx_destruct;
- (id)activeInteraction;
- (id)highlightedView;
- (void)setActiveInteraction:(id)arg1;
- (void)setHighlightedView:(id)arg1;
- (void)setTemplateInterface:(id)arg1;
- (id)templateInterface;

@end
