/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TeaCharts.framework/TeaCharts
 */

@interface TeaCharts.LineSeriesAccessibilityElementProvider : _TtCs12_SwiftObject {
    void currentZone;
    void interactor;
    void seriesElements;
}

@end
