/* Generated by RuntimeBrowser.
 */

@protocol _UIIdentifierDiffer <NSObject>

@required

- (NSIndexSet *)deletedIndexes;
- (bool)hasChanges;
- (NSIndexSet *)insertedIndexes;
- (NSSet *)movePairs;

@end
