/* Generated by RuntimeBrowser.
 */

@protocol CMFallDetectionManagerInternalDelegate <NSObject>

@required

- (void)fallDetectionManagerInternal:(CMFallDetectionManagerInternal *)arg1 didUpdateFallEvent:(CMFallDetectionEvent *)arg2;
- (void)fallDetectionManagerInternalDidStartBackgroundSession:(CMFallDetectionManagerInternal *)arg1;
- (void)fallDetectionManagerInternalDidUpdateEnablementState:(CMFallDetectionManagerInternal *)arg1;

@end
