/* Generated by RuntimeBrowser.
 */

@protocol HDSPWakeDetectionStateMachineEventHandler <HKSPStateMachineEventHandler>

@required

- (void)wakeDetectionEventDue;
- (void)wakeupEventDetected:(NSDate *)arg1;

@end
