/* Generated by RuntimeBrowser.
 */

@protocol SPAccessoryDiscoveryXPCClientProtocol <NSObject>

@required

- (oneway void)accessoryDiscoveryError:(NSError *)arg1;
- (oneway void)discoveredAccessory:(SPDiscoveredAccessory *)arg1;
- (oneway void)lostAccessory:(SPDiscoveredAccessory *)arg1;

@end
