//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString;

@protocol UMUserPersonaLoginSessionManagement
- (_Bool)personaLogoutWithUserODuuid:(NSString *)arg1 withUid:(unsigned int)arg2 WithError:(id *)arg3;
- (_Bool)personaLoginWithUserODuuid:(NSString *)arg1 withUid:(unsigned int)arg2 WithError:(id *)arg3;
@end

