/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DocumentManagerExecutables.framework/DocumentManagerExecutables
 */

@interface DocumentManagerExecutables.DOCPostLaunchBuffer : DocumentManagerExecutables.DOCOperationBuffer {
    void timeout;
}

- (void).cxx_destruct;

@end
