/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXPhotoKitAssetCollectionBlacklistMemoryActionPerformer : PXPhotoKitAssetCollectionBlacklistMemoryFeatureActionPerformer

+ (bool)canPerformOnAssetCollectionReference:(id)arg1 withInputs:(id)arg2;
+ (id)createActivityWithTitle:(id)arg1 actionType:(id)arg2 actionSystemImageName:(id)arg3;
+ (id)createAlertActionWithTitle:(id)arg1 handler:(id /* block */)arg2;
+ (id)localizedTitleForUseCase:(unsigned long long)arg1 assetCollectionReference:(id)arg2 withInputs:(id)arg3;
+ (id)systemImageNameForAssetCollectionReference:(id)arg1 withInputs:(id)arg2;

- (bool)_didUserConfirmDeleteOfMemory;
- (id)_disambiguationActionsForAlert:(bool)arg1 withActionHandler:(id /* block */)arg2;
- (bool)_doesUserActionRequireDisambiguation:(id)arg1 outResolvedAction:(id*)arg2 outAlertActionsForDisambiguation:(id*)arg3 alertActionHandler:(id /* block */)arg4;
- (id)disambiguationMenuForUseCase:(unsigned long long)arg1 withMenuActionHandler:(id /* block */)arg2;
- (void)performBackgroundTask;
- (void)performUserInteractionTask;

@end
