/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VFX.framework/VFX
 */

@interface VFXCore.ScriptCodeGen : _TtCs12_SwiftObject {
    void entityManager;
    void isGeneratingForTesting;
    void swiftProjectName;
    void userProjectName;
}

@end
