//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSFileHandle;

@interface NSPipe : NSObject
{
}

+ (id)pipe;
+ (id)allocWithZone:(struct _NSZone *)arg1;
- (void)_closeOnDealloc;
@property(readonly, retain) NSFileHandle *fileHandleForWriting;
@property(readonly, retain) NSFileHandle *fileHandleForReading;
- (id)init;

@end

