/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Transparency.framework/Transparency
 */

@interface LogHead : GPBMessage

@property (nonatomic) int application;
@property (nonatomic) unsigned long long logBeginningMs;
@property (nonatomic, copy) NSData *logHeadHash;
@property (nonatomic) unsigned long long logSize;
@property (nonatomic) int logType;
@property (nonatomic) unsigned long long revision;
@property (nonatomic) unsigned long long treeId;

+ (id)descriptor;

@end
