/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PersonalizationPortraitInternals.framework/PersonalizationPortraitInternals
 */

@interface PPConnectionsScoredLocationGuardedData : NSObject {
    NSMutableArray * _locations;
    NSMutableSet * _seenValues;
}

- (void).cxx_destruct;
- (id)init;

@end
