/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/FrontBoard.framework/FrontBoard
 */

@interface FBPreferences : BSAbstractDefaultDomain

@property (nonatomic, readonly) bool disableXPCServicesEndpointHack;

+ (id)sharedInstance;

- (void)_bindAndRegisterDefaults;
- (id)_init;

@end
