//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber, NSString;

@interface _DPPrivacyBudgetProperties : NSObject
{
    NSString *_name;
    NSNumber *_interval;
    NSNumber *_intervalBudgetValue;
    NSNumber *_refillInterval;
    NSNumber *_refillAmount;
}

+ (id)budgetMaintenanceSchedule;
+ (id)allBudgetPropertiesKeys;
+ (id)budgetPropertiesFromFile:(id)arg1;
+ (id)budgetPropertiesForKey:(id)arg1;
+ (void)initializeAllBudgetProperties;
+ (id)budgetPropertiesFromDictionary:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSNumber *refillAmount; // @synthesize refillAmount=_refillAmount;
@property(retain, nonatomic) NSNumber *refillInterval; // @synthesize refillInterval=_refillInterval;
@property(retain, nonatomic) NSNumber *intervalBudgetValue; // @synthesize intervalBudgetValue=_intervalBudgetValue;
@property(retain, nonatomic) NSNumber *interval; // @synthesize interval=_interval;
@property(readonly, copy, nonatomic) NSString *name; // @synthesize name=_name;
- (id)description;
- (id)initWithDictionary:(id)arg1;
- (id)init;

@end

