//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (_DPTArguments)
- (id)dp_wordRecordsFromCSVString;
- (id)dp_numbersFromCSVString;
- (id)dp_stringsFromCSVString;
@end

