/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon
 */

@interface HDWorkoutSessionTaskServer : HDStandardTaskServer <HDWorkoutDataDestination, HDWorkoutDataSource, HDWorkoutSessionObserver, HKDataFlowLinkProcessor, HKWorkoutSessionServerInterface> {
    <HDWorkoutDataAccumulator> * _accumulator;
    HDWorkoutBuilderEntity * _builderEntity;
    HKSource * _clientSource;
    NSObject<OS_dispatch_queue> * _queue;
    HDWorkoutSessionServer * _sessionServer;
    HKWorkoutSessionTaskConfiguration * _taskConfiguration;
    HKDataFlowLink * _workoutDataFlowLink;
}

@property <HDWorkoutDataAccumulator> *accumulator;
@property (nonatomic, readonly, copy) HKSource *clientSource;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) bool requiresCoreLocationAssertion;
@property (nonatomic, readonly) bool shouldStopPreviousSession;
@property (readonly) Class superclass;
@property (nonatomic, readonly) bool supportsAppRelaunchForRecovery;
@property (nonatomic, readonly) <HDWorkoutDataAccumulator> *workoutDataAccumulator;
@property (readonly) unsigned long long workoutDataDestinationState;
@property (readonly) HKDataFlowLink *workoutDataFlowLink;
@property (readonly, copy) NSUUID *workoutDataProcessorUUID;

+ (Class)configurationClass;
+ (id)createTaskServerWithUUID:(id)arg1 configuration:(id)arg2 client:(id)arg3 delegate:(id)arg4 error:(id*)arg5;
+ (id)requiredEntitlements;
+ (id)taskIdentifier;
+ (bool)validateConfiguration:(id)arg1 client:(id)arg2 error:(id*)arg3;

- (void).cxx_destruct;
- (void)_queue_setupSessionServer;
- (id)accumulator;
- (void)addMetadata:(id)arg1 dataSource:(id)arg2;
- (void)addSamples:(id)arg1 dataSource:(id)arg2;
- (void)addWorkoutEvents:(id)arg1 dataSource:(id)arg2;
- (id)clientSource;
- (void)connectionConfigured;
- (void)connectionInvalidated;
- (id)exportedInterface;
- (id)initWithUUID:(id)arg1 configuration:(id)arg2 client:(id)arg3 clientSource:(id)arg4 delegate:(id)arg5 sessionServer:(id)arg6;
- (void)observeWorkoutSessionServer:(id)arg1;
- (id)remoteInterface;
- (void)remote_recoverWithCompletion:(id /* block */)arg1;
- (void)remote_setTargetState:(long long)arg1 date:(id)arg2 completion:(id /* block */)arg3;
- (bool)requiresCoreLocationAssertion;
- (void)setAccumulator:(id)arg1;
- (void)setAssociatedWorkoutBuilderEntity:(id)arg1;
- (void)setWorkoutDataAccumulator:(id)arg1;
- (bool)shouldStopPreviousSession;
- (bool)supportsAppRelaunchForRecovery;
- (void)updateWorkoutConfiguration:(id)arg1 dataSource:(id)arg2;
- (id)workoutDataAccumulator;
- (void)workoutDataDestination:(id)arg1 didChangeFromState:(unsigned long long)arg2 toState:(unsigned long long)arg3;
- (void)workoutDataDestination:(id)arg1 didUpdateConfiguration:(id)arg2;
- (void)workoutDataDestination:(id)arg1 requestsDataFrom:(id)arg2 to:(id)arg3;
- (void)workoutDataDestination:(id)arg1 requestsFinalDataFrom:(id)arg2 to:(id)arg3 completion:(id /* block */)arg4;
- (unsigned long long)workoutDataDestinationState;
- (id)workoutDataFlowLink;
- (id)workoutDataProcessorUUID;
- (void)workoutSession:(id)arg1 didChangeToState:(long long)arg2 fromState:(long long)arg3 date:(id)arg4;
- (void)workoutSession:(id)arg1 didFailWithError:(id)arg2;
- (void)workoutSession:(id)arg1 didGenerateEvent:(id)arg2;

@end
