//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CoreData/NSXPCStoreServerRequestHandlingPolicy.h>

@interface PLXPCPhotoLibraryStoreServerRequestHandlingPolicy : NSXPCStoreServerRequestHandlingPolicy
{
}

- (id)restrictingReadPredicateForEntity:(id)arg1 fromClientWithContext:(id)arg2;
- (id)_restrictedEntityNamesAllowedForContext:(id)arg1;
- (id)_entityNamesAllowedByRestrictedDataEntitlements:(id)arg1;
- (BOOL)shouldAcceptConnectionsFromClientWithContext:(id)arg1;
- (id)restrictingPullChangeHistoryPredicateForEntity:(id)arg1 fromClientWithContext:(id)arg2;
- (id)restrictingWritePredicateForEntity:(id)arg1 fromClientWithContext:(id)arg2;
- (BOOL)shouldAcceptMetadataChangesFromClientWithContext:(id)arg1;

@end

