//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProVideo/TDreamProgramWrapper.h>

@interface TDreamDistortionFX : TDreamProgramWrapper
{
    int centerUniform;
    int modeUniform;
    float adjustUniform;
    int _mode;
    float _fine;
    struct CGPoint _center;
}

@property(nonatomic) float fine; // @synthesize fine=_fine;
@property(nonatomic) int mode; // @synthesize mode=_mode;
@property(nonatomic) struct CGPoint center; // @synthesize center=_center;
- (void)setUniforms;
- (id)init;

@end

