/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BusinessChatService.framework/BusinessChatService
 */

@interface BCSIdentityService : NSObject <BCSIdentityServiceProtocol> {
    IDSAccount * _businessChatAccount;
    NSMutableDictionary * _idStatusCompletionBlocks;
    NSObject<OS_dispatch_queue> * _serialDispatchQueue;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) NSMutableDictionary *idStatusCompletionBlocks;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *serialDispatchQueue;
@property (readonly) Class superclass;

+ (id)sharedInstance;

- (void).cxx_destruct;
- (void)addIDSIDQueryControllerDelegate;
- (id)businessChatAccount;
- (void)handleIDStatusCompletionBlocksForBizID:(id)arg1 idStatus:(long long)arg2;
- (id)idStatusCompletionBlocks;
- (void)idStatusUpdatedForDestinations:(id)arg1 service:(id)arg2;
- (id)loginID;
- (void)refreshIDStatusForBizID:(id)arg1 completion:(id /* block */)arg2;
- (id)serialDispatchQueue;
- (void)setIdStatusCompletionBlocks:(id)arg1;
- (void)setSerialDispatchQueue:(id)arg1;
- (void)warmBusinessChatAccountCache;

@end
