/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WallpaperKit.framework/WallpaperKit
 */

@interface WKIndicatorView : UIView {
    UIActivityIndicatorView * __activityIndicatorView;
    _UIBackdropView * __backdropView;
    bool  __hasBeenConfigured;
    UILabel * __label;
}

@property (nonatomic, retain) UIActivityIndicatorView *_activityIndicatorView;
@property (nonatomic, retain) _UIBackdropView *_backdropView;
@property (nonatomic) bool _hasBeenConfigured;
@property (nonatomic, retain) UILabel *_label;

- (void).cxx_destruct;
- (id)_activityIndicatorView;
- (id)_backdropView;
- (void)_configureViewIfNeeded;
- (bool)_hasBeenConfigured;
- (id)_label;
- (void)hideViewAndRemoveFromHostingView;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)set_activityIndicatorView:(id)arg1;
- (void)set_backdropView:(id)arg1;
- (void)set_hasBeenConfigured:(bool)arg1;
- (void)set_label:(id)arg1;
- (void)showViewWithMessage:(id)arg1 inHostingView:(id)arg2;

@end
