//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ParsecUI/PRSCardSectionSliceViewController.h>

#import <ParsecUI/NSTextViewDelegate-Protocol.h>

@class NSString, PRSLinkTableCardSection;

@interface PRSLinkTableSliceViewController : PRSCardSectionSliceViewController <NSTextViewDelegate>
{
}

- (id)additionalHeightConstraint;
- (id)textViewMinHeightConstraint;
- (id)textView;
- (id)linkTableSliceView;
- (void)syncAttributes;
- (void)textView:(id)arg1 syncLinks:(id)arg2;
- (id)attributedStringForLinks:(id)arg1;
- (id)attributedStringForSpace;
- (id)attributedStringForLink:(id)arg1;
- (id)textAttributesForURL:(id)arg1;
- (id)textAttributes;
- (struct _NSRange)textView:(id)arg1 willChangeSelectionFromCharacterRange:(struct _NSRange)arg2 toCharacterRange:(struct _NSRange)arg3;
- (id)textView:(id)arg1 willDisplayToolTip:(id)arg2 forCharacterAtIndex:(unsigned long long)arg3;
- (BOOL)textView:(id)arg1 clickedOnLink:(id)arg2 atIndex:(unsigned long long)arg3;
- (void)setAdditionalHeight:(double)arg1;
- (double)height;
- (void)awakeFromNib;
@property(retain, nonatomic) PRSLinkTableCardSection *linkTableCardSection;
- (id)init;
- (id)initWithCardSection:(id)arg1 nibName:(id)arg2;
- (id)initWithLinkTableCardSection:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

