/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSUnitFuelEfficiency : NSDimension <NSSecureCoding>

+ (id)baseUnit;
+ (void)initialize;
+ (id)litersPer100Kilometers;
+ (id)milesPerGallon;
+ (id)milesPerImperialGallon;

@end
