//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVRemoteCore/NSObject-Protocol.h>

@class NSString, _TVRCMediaRemoteKeyboardAdapter;

@protocol _TVRCMediaRemoteKeyboardAdapterDelegate <NSObject>

@optional
- (void)keyboardAdapter:(_TVRCMediaRemoteKeyboardAdapter *)arg1 receivedUnexpectedTextUpdate:(NSString *)arg2;
@end

