//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Spotlight/SPGroupHeadingResult.h>

@class NSString;

@interface SPMetadataGroupHeadingResult : SPGroupHeadingResult
{
    NSString *_focusString;
}

- (void).cxx_destruct;
- (BOOL)supportsFocus;
- (id)rollOverString;
- (BOOL)isSelectable;
- (id)initWithDisplayName:(id)arg1 keyID:(id)arg2 focusString:(id)arg3;

@end

