//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FileProviderDaemon/NSObject-Protocol.h>

@class NSString;

@protocol FPProviderDomainAccessControl <NSObject>
- (BOOL)isAllowedToProvideItemID:(NSString *)arg1 toConsumerWithIdentifier:(NSString *)arg2;
@end

