/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriOntology.framework/SiriOntology
 */

@interface SIRINLUAsrHypothesis : NSObject <NSSecureCoding> {
    double  _probability;
    NSString * _utterance;
    NSUUID * _uuid;
}

@property (nonatomic) double probability;
@property (nonatomic, retain) NSString *utterance;
@property (nonatomic, retain) NSUUID *uuid;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithUtterance:(id)arg1 probability:(double)arg2 uuid:(id)arg3;
- (double)probability;
- (void)setProbability:(double)arg1;
- (void)setUtterance:(id)arg1;
- (void)setUuid:(id)arg1;
- (id)utterance;
- (id)uuid;

@end
