/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion
 */

@interface NTKBundleComplicationDataSourceBundleCache : NSObject {
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _bundleLock;
    NSMutableDictionary * _cachedBundles;
}

+ (id)sharedBundleCache;

- (void).cxx_destruct;
- (id)_init;
- (id)bundleAtPath:(id)arg1;
- (void)dealloc;

@end
