/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion
 */

@interface NTKBasePhotosFace : NTKFace

+ (id)_complicationSlotDescriptors;
+ (bool)_customEditModeIsRows:(long long)arg1 forDevice:(id)arg2;
+ (id)_defaultSelectedComplicationSlotForDevice:(id)arg1;
+ (id)_localizedNameOverrideForCustomEditMode:(long long)arg1 forDevice:(id)arg2;
+ (id)_orderedComplicationSlots;

- (bool)_allowsEditing;
- (bool)_createResourceDirectorySuitableForSharingAtPath:(id)arg1 error:(id*)arg2;
- (id)_localizedNameForComplicationSlot:(id)arg1;
- (id)_resourceDirectorySnapshotKey;
- (bool)_sanitizeFaceConfiguration:(id*)arg1;
- (bool)_shouldSanitizeFaceConfigurationWhenAddingSharedFace;

@end
