//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WorkflowKit/WFVariable.h>

@interface WFAskWhenRunVariable : WFVariable
{
}

- (BOOL)requiresModernVariableSupport;
- (BOOL)supportsAggrandizements;
- (BOOL)isAvailable;
- (id)name;
- (id)icon;
- (void)retrieveContentCollectionWithVariableSource:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)init;

@end

