//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WFObjectHasher : NSObject
{
    struct SipHasher _hasher;
    unsigned long long _hash;
    BOOL _finalized;
}

- (id).cxx_construct;
- (unsigned long long)finalize;
- (id)combineContentsOf:(id)arg1;
- (id)combineBytes:(void *)arg1 size:(unsigned long long)arg2;
- (id)combineInteger:(long long)arg1;
- (id)combineBool:(BOOL)arg1;
- (id)combine:(id)arg1;
- (id)init;

@end

