//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WFWorkflowConflictResolution : NSObject
{
    BOOL _keepLocal;
    BOOL _keepRemote;
    NSString *_localWorkflowID;
    NSString *_remoteWorkflowID;
}

- (void).cxx_destruct;
@property(nonatomic) BOOL keepRemote; // @synthesize keepRemote=_keepRemote;
@property(nonatomic) BOOL keepLocal; // @synthesize keepLocal=_keepLocal;
@property(copy, nonatomic) NSString *remoteWorkflowID; // @synthesize remoteWorkflowID=_remoteWorkflowID;
@property(copy, nonatomic) NSString *localWorkflowID; // @synthesize localWorkflowID=_localWorkflowID;
- (id)description;

@end

