/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/NetworkExtension.framework/NetworkExtension
 */

@interface NEFilterPacketContext : NSObject {
    NEFilterPacketInterpose * _interpose;
}

@property (retain) NEFilterPacketInterpose *interpose;

- (void).cxx_destruct;
- (id)interpose;
- (void)setInterpose:(id)arg1;

@end
