/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TextInputChinese.framework/TextInputChinese
 */

@interface TIWordSearchWubixing : TIWordSearchShapeBased {
    id /* block */  _contactObserver;
    int  _wubiStandard;
}

@property (nonatomic) int wubiStandard;

- (void).cxx_destruct;
- (id)autoconvertWubiXingPrefixes:(id)arg1 option:(unsigned long long)arg2 candidateResultSet:(id)arg3 autoconvertedCandidateArray:(id*)arg4;
- (void)checkWubiStandard;
- (void)dealloc;
- (id)mecabraCreationOptionsDictionary;
- (int)mecabraInputMethodType;
- (void)setWubiStandard:(int)arg1;
- (void*)shouldAutoCommitCode:(id)arg1 withOption:(unsigned long long)arg2;
- (id)uncachedCandidatesForOperation:(id)arg1;
- (void)updateAddressBook;
- (void)updateMecabraState;
- (int)wubiStandard;
- (int)wubiStandardPreference;

@end
