//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <LoginUIKit/NSObject-Protocol.h>

@class NSImage, NSString;

@protocol LUI2UserListDelegate <NSObject>
- (BOOL)isOtherUser:(id)arg1;
- (BOOL)isGuestUser:(id)arg1;
- (BOOL)isUserLoggedIn:(id)arg1;
- (NSString *)detailsOfUser:(id)arg1;
- (NSString *)nameOfUser:(id)arg1;
- (NSImage *)pictureOfUser:(id)arg1;

@optional
- (void)userPressed:(id)arg1;
- (long long)indexOfUserMatchingSearchString:(NSString *)arg1;
@end

