/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppleDepth.framework/AppleDepth
 */

@interface ADStereoExecutorParameters : ADExecutorParameters {
    ADStereoPipelineParameters * _pipelineParameters;
}

@property (nonatomic, readonly, retain) ADStereoPipelineParameters *pipelineParameters;

- (void).cxx_destruct;
- (id)initForPipeline:(id)arg1;
- (id)pipelineParameters;

@end
