//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSAttributedString.h>

@interface NSAttributedString (SocialUIAdditions)
+ (id)inputLineStringStoredIn:(id)arg1;
@property(readonly) BOOL containsFileTransfers; // @dynamic containsFileTransfers;
- (id)messagesToSendForChat:(id)arg1 baseWritingDirection:(long long)arg2 flags:(unsigned long long)arg3;
- (id)_rangesContainingPluginPayloads;
- (id)inputLineFormattedAttributedString;
- (id)storableFormat;
@end

