//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Photos/PHAssetCollection.h>

@class NSData, NSSet, NSString;

@interface PHMemory : PHAssetCollection
{
    NSString *_titleFontName;
}

+ (id)assetListPredicateFromQueryHintObject:(id)arg1;
+ (id)movieDataWithTitleFontName:(id)arg1;
+ (void)generateMemoriesWithOptions:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void).cxx_destruct;
- (unsigned long long)titleFontNameHash;
- (id)titleFontName;
- (long long)assetCollectionSubtype;
- (long long)assetCollectionType;
@property(readonly, nonatomic) NSSet *featuredPeopleIdentifiers;
- (id)movieStateDataForAsset:(id)arg1;
@property(readonly, nonatomic) NSData *movieData;
@property(readonly, nonatomic) NSData *photosGraphData;
@property(readonly, nonatomic) long long photosGraphVersion;
- (double)score;
@property(readonly, nonatomic, getter=isUserCreated) BOOL userCreated;
@property(readonly, nonatomic, getter=isPending) BOOL pending;
- (BOOL)isBookmarked;
@property(readonly, nonatomic, getter=isFavorite) BOOL favorite;
@property(readonly, nonatomic, getter=isRejected) BOOL rejected;
@property(readonly, nonatomic) long long subcategory;
@property(readonly, nonatomic) long long category;
- (id)creationDate;
- (id)localizedSubtitle;
- (id)localizedTitle;
- (id)memory;
- (id)initWithModel:(id)arg1 photoLibrary:(id)arg2;

@end

