/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Silex.framework/Silex
 */

@interface SXTangierTextRenderCollectorItem : NSObject {
    NSString * _componentIdentifier;
    UIView<TSDRepDirectLayerHosting> * _directLayerHost;
    SXTextTangierFlowInfo * _flowInfo;
    SXTextTangierFlowLayout * _flowLayout;
    struct _NSRange { 
        unsigned long long location; 
        unsigned long long length; 
    }  _flowRange;
    SXTextTangierFlowStorage * _flowStorage;
    SXTextTangierTextLayout * _layout;
    bool  _selectable;
    SXTextTangierStorage * _storage;
}

@property (nonatomic, readonly) NSString *componentIdentifier;
@property (nonatomic, readonly) UIView<TSDRepDirectLayerHosting> *directLayerHost;
@property (nonatomic, readonly) SXTextTangierFlowInfo *flowInfo;
@property (nonatomic, retain) SXTextTangierFlowLayout *flowLayout;
@property (nonatomic, readonly) struct _NSRange { unsigned long long x1; unsigned long long x2; } flowRange;
@property (nonatomic, readonly) SXTextTangierFlowStorage *flowStorage;
@property (nonatomic, retain) SXTextTangierTextLayout *layout;
@property (nonatomic, readonly) bool selectable;
@property (nonatomic, retain) SXTextTangierStorage *storage;

- (void).cxx_destruct;
- (void)appendToFlowStorage:(id)arg1;
- (id)componentIdentifier;
- (id)debugDescription;
- (id)description;
- (id)directLayerHost;
- (id)flowInfo;
- (id)flowLayout;
- (id)flowLayoutWithICC:(id)arg1;
- (struct _NSRange { unsigned long long x1; unsigned long long x2; })flowRange;
- (id)flowStorage;
- (id)initWithStorage:(id)arg1 layout:(id)arg2 directLayerHost:(id)arg3 selectable:(bool)arg4 componentIdentifier:(id)arg5;
- (id)layout;
- (bool)selectable;
- (void)setFlowLayout:(id)arg1;
- (void)setLayout:(id)arg1;
- (void)setStorage:(id)arg1;
- (id)storage;
- (void)updateWithLayout:(id)arg1;

@end
