/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ODML.framework/ODML
 */

@interface APOdmlDESRecordManager : APOdmlSingleton {
    NSMutableDictionary * _desRecords;
}

@property (nonatomic, retain) NSMutableDictionary *desRecords;

+ (id)sharedInstance;

- (void).cxx_destruct;
- (void)addAdListToDES:(id)arg1 forRequestID:(id)arg2 listType:(long long)arg3;
- (id)desRecords;
- (id)init;
- (id)recordForRequestID:(id)arg1;
- (void)setDesRecords:(id)arg1;
- (void)updateAdData:(id)arg1 forRequestID:(id)arg2;

@end
