/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaFoundation.framework/MediaFoundation
 */

@interface MediaFoundation.InitiatingPlaybackState : MediaFoundation.State {
    void fromInterruption;
    void metadata;
}

@end
