/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaFoundation.framework/MediaFoundation
 */

@interface MediaFoundation.QueueAssetLoader : _TtCs12_SwiftObject <MFStateDumpable> {
    void delegate;
    void errorController;
    void itemBuffer;
    void itemLoader;
    void loadingCompletions;
    void queueController;
    void reporter;
    void token;
    void wrapAround;
}

@property (nonatomic, readonly) NSDictionary *stateDictionary;

- (id)stateDictionary;

@end
