/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DoNotDisturbServer.framework/DoNotDisturbServer
 */

@interface DNDSRemoteServiceProvider : NSObject <DNDRemoteServiceServerProtocol, NSXPCListenerDelegate> {
    NSMapTable * _clientConnectionDetailsByConnection;
    DNDSClientDetailsProvider * _clientDetailsProvider;
    <DNDSRemoteServiceProviderDelegate> * _delegate;
    NSXPCListener * _listener;
}

@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <DNDSRemoteServiceProviderDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)_clientDetailsForClientIdentifier:(id)arg1 clientConnection:(id)arg2;
- (void)_handleClientConnectionInterrupted:(id)arg1;
- (void)_handleClientConnectionInvalidated:(id)arg1;
- (void)_iterateClientConnectionsToSendWithHandler:(id /* block */)arg1;
- (void)_registerOrMutateConnectionDetailsForClientConnection:(id)arg1 handler:(id /* block */)arg2;
- (void)_unregisterConnectionDetailsForClientConnection:(id)arg1;
- (void)dealloc;
- (id)delegate;
- (void)getActiveModeAssertionWithRequestDetails:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)getBehaviorSettingsWithRequestDetails:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)getLatestModeAssertionInvalidationWithRequestDetails:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)getPhoneCallBypassSettingsWithRequestDetails:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)getScheduleSettingsWithRequestDetails:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)handleModeAssertionUpdateResult:(id)arg1;
- (void)handleStateUpdate:(id)arg1;
- (void)handleUpdatedBehaviorSettings:(id)arg1;
- (void)handleUpdatedPhoneCallBypassSettings:(id)arg1;
- (void)handleUpdatedScheduleSettings:(id)arg1;
- (id)initWithClientDetailsProvider:(id)arg1;
- (void)invalidate;
- (void)invalidateActiveModeAssertionWithDetails:(id)arg1 reasonOverride:(unsigned long long)arg2 requestDetails:(id)arg3 completionHandler:(id /* block */)arg4;
- (void)invalidateAllActiveModeAssertionsWithRequestDetails:(id)arg1 completionHandler:(id /* block */)arg2;
- (bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (void)queryStateWithRequestDetails:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)registerForAssertionUpdatesWithRequestDetails:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)registerForSettingsUpdatesWithRequestDetails:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)registerForStateUpdatesWithRequestDetails:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)resolveBehaviorForEventDetails:(id)arg1 requestDetails:(id)arg2 completionHandler:(id /* block */)arg3;
- (void)resume;
- (void)setBehaviorSettings:(id)arg1 withRequestDetails:(id)arg2 completionHandler:(id /* block */)arg3;
- (void)setDelegate:(id)arg1;
- (void)setPhoneCallBypassSettings:(id)arg1 withRequestDetails:(id)arg2 completionHandler:(id /* block */)arg3;
- (void)setScheduleSettings:(id)arg1 withRequestDetails:(id)arg2 completionHandler:(id /* block */)arg3;
- (void)takeModeAssertionWithDetails:(id)arg1 requestDetails:(id)arg2 completionHandler:(id /* block */)arg3;

@end
