/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.PPTTagFeedServiceConfigFetcher : _TtCs12_SwiftObject {
    void cloudContext;
    void configurationManager;
    void contentConfigData;
}

@end
