/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.OfferAdSegmentProvider : _TtCs12_SwiftObject {
    void appConfigurationManager;
    void needsUpdate;
    void offerManager;
}

@end
