//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AVFoundation/AVMediaSelectionOption.h>

@class NSNumber, NSString;

@interface AVMediaSelectionOption (AVPlayerController)
+ (id)avkit_autoOption;
+ (id)avkit_offOption;
- (long long)languageCompare:(id)arg1 currentLanguageCode:(id)arg2 currentLanguageIdentifier:(id)arg3;
@property(readonly, getter=isAuxiliary) BOOL auxiliary;
@property(readonly, getter=isEasyReader) BOOL easyReader;
@property(readonly, getter=isCC) BOOL CC;
@property(readonly, getter=isSDH) BOOL SDH;
@property(readonly, getter=isMain) BOOL main;
@property(readonly, getter=isAC3Only) BOOL AC3Only;
@property(readonly) NSNumber *avkit_persistentIdentifier;
- (id)avkit_title;
@property(readonly) NSString *mediaRemoteIdentifier;
@property(readonly) NSString *shortLocalizedDisplayName;
@property(readonly) NSString *localizedDisplayName;
@end

