/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppPredictionInternal.framework/AppPredictionInternal
 */

@interface ATXBiomeStreamFeedbackHandler : NSObject <NSCoding> {
    BPSPublisher * _appLaunchPublisher;
    BPSPublisher * _blendingPublisher;
    <BMBookmark> * _bookmark;
    NSString * _bookmarkPath;
    unsigned long long  _classVersion;
    BPSPublisher * _clientModelPublisher;
    NSSet * _consumerSubTypeStringSet;
    ATXFeedbackSessionRouter * _feedbackSessionRouter;
    BPSPublisher * _intentPublisher;
    BPSPublisher * _predictionContextPublisher;
    NSObject<OS_dispatch_queue> * _queue;
    <ATXBiomeSessionProducerProtocol> * _sessionProducer;
    BPSPublisher * _uiStreamPublisher;
}

@property (nonatomic, retain) BPSPublisher *appLaunchPublisher;
@property (nonatomic, retain) BPSPublisher *blendingPublisher;
@property (nonatomic, retain) BPSPublisher *clientModelPublisher;
@property (nonatomic, retain) BPSPublisher *intentPublisher;
@property (nonatomic, retain) BPSPublisher *predictionContextPublisher;
@property (nonatomic, retain) BPSPublisher *uiStreamPublisher;

+ (id)_currentPredictionContext;
+ (id)_dataFromFileHandle:(id)arg1;
+ (bool)_fileExistsAtPath:(id)arg1;
+ (bool)_fileSizeWithinLimits:(id)arg1;
+ (id)_timeBasedMergedOnStoreStreamPublisher:(id)arg1 otherStoreStreamPublishers:(id)arg2;
+ (id)feedbackHandlerWithBookmarkPath:(id)arg1 feedbackRouter:(id)arg2 sessionProducer:(id)arg3 consumerSubTypeStringSet:(id)arg4;

- (void).cxx_destruct;
- (id)_contextPublisherPublisher:(id)arg1 consumerSubTypeStringSet:(id)arg2;
- (id)_filteredCacheUpdateClientModelPublisher:(id)arg1;
- (id)appLaunchPublisher;
- (id)blendingPublisher;
- (id)clientModelPublisher;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)hash;
- (id)inferredUIStreamForConsumerSubTypeStringSet:(id)arg1;
- (id)init;
- (id)initWithBookmark:(id)arg1 bookmarkPath:(id)arg2 classVersion:(unsigned long long)arg3 feedbackRouter:(id)arg4 sessionProducer:(id)arg5 consumerSubTypeStringSet:(id)arg6;
- (id)initWithCoder:(id)arg1;
- (id)intentPublisher;
- (bool)isEqual:(id)arg1;
- (bool)isEqualToATXBiomeStreamFeedbackHandler:(id)arg1;
- (void)persistBookmark;
- (id)predictionContextPublisher;
- (void)processInteractionFeedback;
- (void)setAppLaunchPublisher:(id)arg1;
- (void)setBlendingPublisher:(id)arg1;
- (void)setClientModelPublisher:(id)arg1;
- (void)setIntentPublisher:(id)arg1;
- (void)setPredictionContextPublisher:(id)arg1;
- (void)setUiStreamPublisher:(id)arg1;
- (id)uiStreamPublisher;

@end
