/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VoiceShortcutClient.framework/VoiceShortcutClient
 */

@interface WFWorkflowRunnerClient : NSObject {
    WFWorkflowRunningContext * _context;
    <WFWorkflowRunnerClientDelegate> * _delegate;
    id  _progressSubscriber;
    WFWorkflowRunRequest * _runRequest;
}

@property (nonatomic, retain) WFWorkflowRunningContext *context;
@property (nonatomic) <WFWorkflowRunnerClientDelegate> *delegate;
@property (nonatomic, retain) id progressSubscriber;
@property (nonatomic, readonly) WFWorkflowRunRequest *runRequest;

- (void).cxx_destruct;
- (void)beginObservingProgressForWorkflowWithRunningContext:(id)arg1;
- (id)context;
- (id)delegate;
- (id)initWithRunRequest:(id)arg1;
- (id)progressSubscriber;
- (id)runRequest;
- (void)setContext:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setProgressSubscriber:(id)arg1;
- (void)start;
- (void)stop;
- (void)stopObservingRunProgress;

@end
