//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <PassKitCore/PKSpringAnimationFactory.h>

@interface PKUISpringAnimationFactory : PKSpringAnimationFactory
{
    CDUnknownBlockType _animationDelayHandler;
    double _maximumVendedDelay;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) double maximumVendedDelay; // @synthesize maximumVendedDelay=_maximumVendedDelay;
@property(copy, nonatomic) CDUnknownBlockType animationDelayHandler; // @synthesize animationDelayHandler=_animationDelayHandler;
- (id)_basicAnimationForView:(id)arg1 withKeyPath:(id)arg2;
- (id)_springAnimationForView:(id)arg1 withKeyPath:(id)arg2;
- (id)springAnimationForView:(id)arg1 withKeyPath:(id)arg2;

@end

