/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AXMediaUtilities.framework/AXMediaUtilities
 */

@interface AXMVisionFeatureFaceAttributes : NSObject <NSSecureCoding> {
    long long  _ageCategory;
    long long  _baldCategory;
    long long  _eyesCategory;
    long long  _faceHairCategory;
    long long  _genderCategory;
    long long  _glassesCategory;
    long long  _hairColorCategory;
    NSDictionary * _results;
    long long  _smilingCategory;
}

@property (nonatomic, readonly) long long ageCategory;
@property (nonatomic, readonly) long long baldCategory;
@property (nonatomic, readonly) long long eyesCategory;
@property (nonatomic, readonly) long long faceHairCategory;
@property (nonatomic, readonly) long long genderCategory;
@property (nonatomic, readonly) long long glassesCategory;
@property (nonatomic, readonly) long long hairColorCategory;
@property (nonatomic, retain) NSDictionary *results;
@property (nonatomic, readonly) long long smilingCategory;

+ (bool)supportsSecureCoding;
+ (id)unitTestingFaceAttributes;

- (void).cxx_destruct;
- (long long)_AXMAgeCategoryForVisionCategoryIdentifier:(id)arg1;
- (long long)_AXMBaldCategoryForVisionCategoryIdentifier:(id)arg1;
- (long long)_AXMEyesCategoryForVisionCategoryIdentifier:(id)arg1;
- (long long)_AXMFaceHairCategoryForVisionCategoryIdentifier:(id)arg1;
- (long long)_AXMGenderCategoryForVisionCategoryIdentifier:(id)arg1;
- (long long)_AXMGlassesCategoryForVisionCategoryIdentifier:(id)arg1;
- (long long)_AXMHairColorCategoryForVisionCategoryIdentifier:(id)arg1;
- (long long)_AXMSmilingCategoryForVisionCategoryIdentifier:(id)arg1;
- (id)_accessibilityLabelForAgeCategory;
- (id)_accessibilityLabelForBaldCategory;
- (id)_accessibilityLabelForEyesCategory;
- (id)_accessibilityLabelForFaceHairCategory;
- (id)_accessibilityLabelForGlassesCategory;
- (id)_accessibilityLabelForHairColorCategory;
- (id)_accessibilityLabelForSmilingCategory;
- (id)accessibilityLabelForAttributes;
- (long long)ageCategory;
- (long long)baldCategory;
- (void)encodeWithCoder:(id)arg1;
- (long long)eyesCategory;
- (long long)faceHairCategory;
- (long long)genderCategory;
- (long long)glassesCategory;
- (long long)hairColorCategory;
- (id)initWithAVMetadataFaceObject:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithVisionFaceAttributes:(id)arg1;
- (id)results;
- (void)setResults:(id)arg1;
- (long long)smilingCategory;

@end
