//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Contacts/NSObject-Protocol.h>

@class NSDictionary, NSString;

@protocol CNRecordCoreDataPredicateMapping <NSObject>
@property(readonly, nonatomic) Class valueClass;
@property(readonly, nonatomic) BOOL isRelationship;
@property(readonly, nonatomic) BOOL isMultiValue;
@property(readonly, retain, nonatomic) NSDictionary *coreDataBitMaskedValuesMap;
@property(readonly, nonatomic) long long coreDataBitMask;
@property(readonly, retain, nonatomic) NSDictionary *subCoreDataPredicatePropertiesByKey;
@property(readonly, copy, nonatomic) NSString *coreDataPredicateKeyPath;
@end

