//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Contacts/CNContactStore.h>

@protocol CNSiriIntelligenceSettingsProtocol, SGSuggestionsServiceContactsProtocol;

@interface CNSuggestedContactStore : CNContactStore
{
    id <SGSuggestionsServiceContactsProtocol> _suggestionService;
    id <CNSiriIntelligenceSettingsProtocol> _siriIntelligenceSettings;
}

+ (BOOL)isSuggestionsSupported;
+ (id)storeIdentifier;
+ (id)storeInfoClasses;
- (void).cxx_destruct;
@property(retain, nonatomic) id <CNSiriIntelligenceSettingsProtocol> siriIntelligenceSettings; // @synthesize siriIntelligenceSettings=_siriIntelligenceSettings;
@property(retain, nonatomic) id <SGSuggestionsServiceContactsProtocol> suggestionService; // @synthesize suggestionService=_suggestionService;
- (BOOL)executeSaveRequest:(id)arg1 error:(id *)arg2;
- (BOOL)_processSuggestions:(id)arg1 error:(id *)arg2 withBlock:(CDUnknownBlockType)arg3;
- (id)unifiedContactsMatchingPredicate:(id)arg1 keysToFetch:(id)arg2 error:(id *)arg3;
- (BOOL)enumerateContactsAndMatchInfoWithFetchRequest:(id)arg1 error:(id *)arg2 usingBlock:(CDUnknownBlockType)arg3;
- (id)originForSuggestion:(id)arg1 error:(id *)arg2;
- (id)requestAccessForEntityType:(long long)arg1;
- (id)initWithSuggestionsService:(id)arg1 siriIntelligenceSettings:(id)arg2;
- (id)init;

@end

