/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BannerKit.framework/BannerKit
 */

@interface BNBannerClientContainerViewController : UIViewController <BNBannerClientContainer> {
    <BSInvalidatable> * _deferringRule;
    <BNBannerClientContainerDelegate> * _delegate;
    _BNPanGestureServiceProxy * _panGestureProxy;
    <BNPresentable> * _presentable;
    UIScene * _scene;
    NSMutableArray * _transitionContextStack;
}

@property (readonly, copy) NSString *debugDescription;
@property (getter=isDeferringFocus, nonatomic, readonly) bool deferringFocus;
@property (nonatomic) <BNBannerClientContainerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) <BNPresentable> *presentable;
@property (nonatomic, readonly) UIScene *scene;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_acquireDeferringRuleIfNecessary;
- (bool)_canShowWhileLocked;
- (void)_handlePanGestureProxyAction:(id)arg1;
- (void)_handleSizeTransitionCompleteAction:(id)arg1;
- (void)_handleViewWillTransitionToSizeAction:(id)arg1 shouldFence:(bool)arg2;
- (void)_invalidateDeferringRule;
- (void)_performActionsForUIScene:(id)arg1 withUpdatedFBSScene:(id)arg2 settingsDiff:(id)arg3 fromSettings:(id)arg4 transitionContext:(id)arg5 lifecycleActionType:(unsigned int)arg6;
- (id)_respondToActions:(id)arg1 forFBSScene:(id)arg2 inUIScene:(id)arg3 fromTransitionContext:(id)arg4;
- (void)_setPreferredContentSize:(struct CGSize { double x1; double x2; })arg1 shouldFence:(bool)arg2;
- (void)_setPresentableBannerAppearState:(int)arg1 reason:(id)arg2;
- (void)_setPresentableUserInteractionInProgress:(bool)arg1;
- (void)_setPresentableViewControllerAppearState:(int)arg1;
- (void)bs_traitCollectionDidChange:(id)arg1 forManagedTraitEnvironment:(id)arg2;
- (void)dealloc;
- (id)delegate;
- (id)initWithScene:(id)arg1 presentable:(id)arg2;
- (bool)isDeferringFocus;
- (id)keyWindowForScreen:(id)arg1;
- (void)preferredContentSizeDidChangeForChildContentContainer:(id)arg1;
- (id)presentable;
- (id)scene;
- (void)setDelegate:(id)arg1;
- (void)setPreferredContentSize:(struct CGSize { double x1; double x2; })arg1;
- (bool)shouldAutomaticallyForwardAppearanceMethods;
- (void)viewDidLoad;
- (void)viewWillLayoutSubviews;

@end
