/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ChronoKit.framework/ChronoKit
 */

@interface ChronoKit.PowerlogUpdateService : _TtCs12_SwiftObject {
    void _entries;
    void lock;
    void provider;
}

@end
