//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "ABCommand.h"

@class ABGroup, NSMutableArray;

@interface ABShowAsCommand : ABCommand
{
    NSMutableArray *_selectedMembers;
    ABGroup *_selectedGroup;
    long long _personType;
}

- (BOOL)doIt;
- (void)redoIt;
- (void)undoIt;
- (void)_showAs;
- (void)dealloc;
- (id)initWithGroup:(id)arg1 members:(id)arg2 showAs:(long long)arg3 addressBook:(id)arg4;

@end

