//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSButton.h>

@class NSColor;

@interface SiriUIButton : NSButton
{
    NSColor *_titleColor;
    NSColor *_highligtTitleColor;
}

+ (Class)cellClass;
+ (id)buttonWithImageTemplate:(id)arg1;
- (void).cxx_destruct;
@property struct NSEdgeInsets titleEdgeInsets;
@property struct NSEdgeInsets imageEdgeInsets;
- (void)setHighlightTitleColor:(id)arg1;
- (void)setTitleColor:(id)arg1;
- (void)setTarget:(id)arg1 action:(SEL)arg2;
- (void)setTitle:(id)arg1;
- (void)updateLayer;
- (BOOL)wantsUpdateLayer;
- (BOOL)allowsVibrancy;
- (void)_commonInit;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;

@end

