//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AssistiveControlSupport/ACSHPanelButtonView.h>

@interface ACSHPanelRadioButtonView : ACSHPanelButtonView
{
    BOOL _isActive;
}

@property(nonatomic) BOOL isActive; // @synthesize isActive=_isActive;
- (id)accessibilityAttributeValue:(id)arg1;
- (id)accessibilityAttributeNames;

@end

