//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSPrefCrossFadeWindow;

@interface NSPrefCrossFadeWindowMoveHelper : NSObject
{
    struct __CFRunLoopTimer *_moveTimer;
    struct __CFRunLoop *_runLoop;
    double _startTime;
    double _totalTime;
    double _percent;
    NSPrefCrossFadeWindow *_window;
    struct CGRect _frameDelta;
    struct CGRect _startFrame;
    double _screenMaxY;
    BOOL _done;
    BOOL _displayFlag;
}

- (void).cxx_destruct;
- (void)_stopAnimation;
- (void)_doAnimation:(BOOL)arg1;
- (void)_resizeWindow:(id)arg1 toFrame:(struct CGRect)arg2 display:(BOOL)arg3;
- (void)dealloc;
- (id)init;

@end

