//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@interface NSPrefAnimatedView : NSView
{
    double mPercent;
    unsigned long long mAnimationEffect;
    struct CGImage *mSourceImage;
}

+ (struct CGImage *)createCGImageOfView:(id)arg1 rect:(struct CGRect)arg2 superview:(id)arg3 windowRect:(struct CGRect)arg4;
+ (struct CGImage *)createCGImageOfView:(id)arg1 rect:(struct CGRect)arg2 superview:(id)arg3;
+ (struct CGImage *)createCGImageOfRect:(struct CGRect)arg1 inWindow:(id)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (void)didStopAnimation;
- (void)willStartAnimation;
- (void)setAnimationEffect:(unsigned long long)arg1;
- (void)setPercent:(double)arg1;
- (BOOL)isOpaque;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

