/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosGraph.framework/PhotosGraph
 */

@interface PGGraphOptimizedEdge : PGGraphEdge

- (void)checkConsistencyOfProperties:(id)arg1 withExtraPropertyKeys:(id)arg2;
- (id)description;
- (id)edgeDescription;
- (float)weight;

@end
