//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <AuthKit/NSSecureCoding-Protocol.h>

@class NSData, NSNumber;

@interface AKIconContext : NSObject <NSSecureCoding>
{
    NSData *_data;
    NSNumber *_scale;
    unsigned long long _maskingStyle;
}

+ (BOOL)supportsSecureCoding;
- (void).cxx_destruct;
@property(nonatomic) unsigned long long maskingStyle; // @synthesize maskingStyle=_maskingStyle;
@property(retain, nonatomic) NSNumber *scale; // @synthesize scale=_scale;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

