/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsArticles.framework/NewsArticles
 */

@interface NewsArticles.EndOfArticleEventHandler : _TtCs12_SwiftObject {
    void delegate;
    void interactor;
    void router;
    void tracker;
}

@end
