/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsArticles.framework/NewsArticles
 */

@interface NewsArticles.EndOfArticlePublisherViewRenderer : _TtCs12_SwiftObject {
    void commandCenter;
    void imageCache;
    void styler;
}

@end
