//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MemoriesDelegate : NSObject
{
}

+ (void)setCurrentProject:(id)arg1;
+ (long long)playbackPixelCount;
+ (BOOL)updateProjectAndCachesOnPhotosLibraryChange;
+ (BOOL)forceTeardownDisplayOnProjectChange;
+ (float)duckingAmount;
+ (unsigned long long)exportFrameRateMode;
+ (unsigned long long)playbackFrameRateMode;
+ (BOOL)shouldPlaySlowMoWhenPreviewing;
+ (id)activeCoreProjectViewController;
+ (void)nukeCaches;
+ (id)currentProject;
+ (BOOL)ignoreReadOnly;
+ (BOOL)allowSaving;

@end

