//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Memories/PHAssetWriter.h>

@class NSData;

__attribute__((visibility("hidden")))
@interface PHImageAssetWriter : PHAssetWriter
{
    NSData *_data;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
- (unsigned long long)estimatedOutputSizeWithError:(id *)arg1;
- (id)transfer;
- (id)request;

@end

