/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GameCenterUICore.framework/GameCenterUICore
 */

@interface GKTextStylePhone : GKTextStyle

+ (double)standardFontSize;

- (id)cellActionItem;
- (id)header1;
- (id)header2;
- (id)header4;
- (id)sectionCaptionSmall;
- (id)signInTitle;
- (id)smallInfo;

@end
