//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <NearField/NFSession.h>

#import <NearField/NFFieldDetectSessionCallbacks-Protocol.h>

@class NFWeakReference, NSString;
@protocol NFFieldDetectSessionDelegate;

@interface NFFieldDetectSession : NFSession <NFFieldDetectSessionCallbacks>
{
    NFWeakReference *_delegate;
    BOOL _fieldNotificationSent;
}

- (void)didEndUnexpectedly;
- (void)didDetectFieldNotification:(id)arg1;
- (void)didDetectField:(BOOL)arg1;
@property id <NFFieldDetectSessionDelegate> delegate;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

