//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <NearField/NSSecureCoding-Protocol.h>

@class NSString;

@interface NFSignatureInfo : NSObject <NSSecureCoding>
{
    NSString *_rsaCert;
    NSString *_eccCert;
    NSString *_eckaCert;
    NSString *_seid;
    NSString *_platformId;
    NSString *_jsblCounter;
    unsigned long long _certificateVersion;
}

+ (BOOL)supportsSecureCoding;
@property(readonly, nonatomic) unsigned long long certificateVersion; // @synthesize certificateVersion=_certificateVersion;
@property(readonly, nonatomic) NSString *jsblCounter; // @synthesize jsblCounter=_jsblCounter;
@property(readonly, nonatomic) NSString *platformId; // @synthesize platformId=_platformId;
@property(readonly, nonatomic) NSString *seid; // @synthesize seid=_seid;
@property(readonly, nonatomic) NSString *eckaCert; // @synthesize eckaCert=_eckaCert;
@property(readonly, nonatomic) NSString *eccCert; // @synthesize eccCert=_eccCert;
@property(readonly, nonatomic) NSString *rsaCert; // @synthesize rsaCert=_rsaCert;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)description;
- (void)dealloc;
- (id)initWithDictionary:(id)arg1;

@end

