//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"
#import "TTMergeableStringIDTracker.h"

@class NSObject<TTMergeableStringUndoCommand>, TTMergeableString, TTMergeableUndoString;

@protocol TTMergeableStringUndoCommand <NSObject, TTMergeableStringIDTracker>
- (BOOL)coalesceWith:(NSObject<TTMergeableStringUndoCommand> *)arg1 inString:(TTMergeableString *)arg2;
- (void)applyToString:(TTMergeableUndoString *)arg1;
@end

