/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

@interface CKConversationSearchResultsController : UITableViewController <UISearchResultsUpdating> {
    CKSpotlightQuery * _currentQuery;
    <CKConversationResultsControllerDelegate> * _delegate;
    bool  _gotTopConversationResults;
    NSArray * _messageResults;
    NSString * _selectedChatGUID;
    CSSearchQuery * _topConversationsQuery;
    NSArray * _topConversationsResults;
}

@property (nonatomic, retain) CKSpotlightQuery *currentQuery;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <CKConversationResultsControllerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic) bool gotTopConversationResults;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) NSArray *messageResults;
@property (nonatomic, readonly) NSArray *searchResults;
@property (nonatomic, retain) NSString *selectedChatGUID;
@property (readonly) Class superclass;
@property (nonatomic, retain) CSSearchQuery *topConversationsQuery;
@property (nonatomic, retain) NSArray *topConversationsResults;

- (void).cxx_destruct;
- (void)_contentSizeCategoryDidChange:(id)arg1;
- (Class)_conversationListCellClass;
- (void)_reloadDataForNewResults;
- (void)_selectChatGUID:(id)arg1;
- (id)_topConversationsQueryForText:(id)arg1;
- (void)_updateTableViewRowHeights;
- (void)cancelCurrentQuery;
- (id)currentQuery;
- (void)dealloc;
- (id)delegate;
- (bool)gotTopConversationResults;
- (void)loadView;
- (id)messageResults;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)searchEnded;
- (id)searchResults;
- (id)selectedChatGUID;
- (void)setCurrentQuery:(id)arg1;
- (void)setCurrentSearchResultSelected:(bool)arg1;
- (void)setDelegate:(id)arg1;
- (void)setGotTopConversationResults:(bool)arg1;
- (void)setMessageResults:(id)arg1;
- (void)setSelectedChatGUID:(id)arg1;
- (void)setTopConversationsQuery:(id)arg1;
- (void)setTopConversationsResults:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (bool)tableView:(id)arg1 shouldIndentWhileEditingRowAtIndexPath:(id)arg2;
- (id)topConversationsQuery;
- (void)topConversationsQueryCompletedWithResults:(id)arg1;
- (id)topConversationsResults;
- (void)updateSearchResultsForSearchController:(id)arg1;
- (void)viewDidLoad;

@end
