/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

@interface CKModalTranscriptController : CKShareSheetChatController {
    bool  _alreadySetUp;
    bool  _cameraSelectionDisabled;
    NSMutableArray * _deferredInsertMediaObjectBlocks;
    CKChatEagerUploadController * _eagerUploadController;
    int  _entryViewInvisible;
    bool  _forceMMS;
    bool  _mimeType;
    NSMutableArray * _partsToInsert;
    NSMutableArray * _typesToInsert;
}

@property (nonatomic, retain) NSMutableArray *deferredInsertMediaObjectBlocks;
@property (nonatomic, retain) CKChatEagerUploadController *eagerUploadController;
@property (nonatomic) bool forceMMS;
@property (nonatomic) bool mimeType;

- (void).cxx_destruct;
- (bool)_canShowWhileLocked;
- (void)_conversationListDidFinishLoading:(id)arg1;
- (bool)_deviceIsLocked;
- (bool)_insertMediaObject:(id)arg1;
- (void)_insertMediaObjectAndReturnFrame:(id)arg1 completion:(id /* block */)arg2;
- (double)_maxEntryViewHeight;
- (double)_offsetForScreenWidth:(double)arg1 containerWidth:(double)arg2 windowOffset:(struct CGPoint { double x1; double x2; })arg3;
- (void)_setConversationDeferredSetup;
- (void)_setEntryViewVisible:(bool)arg1;
- (bool)_shouldAllowCameraAttachments;
- (bool)_shouldUseDefaultFirstResponder;
- (bool)_shouldUseExistingConversations;
- (id)deferredInsertMediaObjectBlocks;
- (void)disableCameraAttachments;
- (id)eagerUploadController;
- (bool)forceMMS;
- (bool)getContainerWidth:(double*)arg1 offset:(double*)arg2;
- (void)hideEntryViewContent:(bool)arg1;
- (id)initWithNavigationController:(id)arg1;
- (void)insertData:(id)arg1 MIMEType:(id)arg2 exportedFilename:(id)arg3;
- (void)insertFileURL:(id)arg1 filename:(id)arg2 transcoderUserInfo:(id)arg3 fullyRealizedPreview:(id)arg4 rawPreview:(id)arg5 appendedVideoURL:(id)arg6 completion:(id /* block */)arg7;
- (void)insertMessage:(id)arg1 appProxy:(id)arg2;
- (void)insertRichLinkWithURL:(id)arg1 data:(id)arg2;
- (bool)messageEntryViewShouldBeginEditing:(id)arg1;
- (bool)mimeType;
- (id)proposedParticipantHandles;
- (void)registerForNotifications;
- (void)sendComposition:(id)arg1;
- (void)setCanEditRecipients:(bool)arg1;
- (void)setComposition:(id)arg1;
- (void)setDeferredInsertMediaObjectBlocks:(id)arg1;
- (void)setEagerUploadController:(id)arg1;
- (void)setForceMMS:(bool)arg1;
- (void)setMimeType:(bool)arg1;
- (void)setPendingAddresses:(id)arg1;
- (void)setShouldDisableEntryField:(bool)arg1;
- (void)setTextEntryContentsVisible:(bool)arg1;
- (bool)shouldDismissAfterSend;
- (void)viewWillAppear:(bool)arg1;
- (void)viewWillTransitionToSize:(struct CGSize { double x1; double x2; })arg1 withTransitionCoordinator:(id)arg2;

@end
