/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

@interface CKWatchfaceInProcessPreviewGenerator : NSObject <CKWatchfacePreviewing>

+ (void)generateFacePreviewImageFromUrl:(id)arg1 completionBlock:(id /* block */)arg2;
+ (Class)implementation;

@end
