/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeAutomationInternal.framework/HomeAutomationInternal
 */

@interface HomeAutomationInternal.ClimateResponses : HomeAutomationInternal.NumericEntityResponses

@end
