/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TextInput.framework/TextInput
 */

@interface TIInputModeParser : NSObject

+ (id)invalidInputModeIdentifierCharacterSet;
+ (id)parseInputMode:(id)arg1;
+ (id)stringByReplacingInvalidCharactersWithUnderscores:(id)arg1;

@end
