/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppPredictionInternal.framework/AppPredictionInternal
 */

@interface ATXAnchorModelPhase1TrainingResult : NSObject {
    NSString * _candidateId;
    double  _classConditionalProbability;
    ATXAnchorModelPBLaunchHistoryMetadata * _launchHistory;
    long long  _numUniqueAnchorOccurrencesWithUniqueCandidateOccurrence;
    double  _posteriorProbability;
}

@property (nonatomic, retain) NSString *candidateId;
@property (nonatomic) double classConditionalProbability;
@property (nonatomic, retain) ATXAnchorModelPBLaunchHistoryMetadata *launchHistory;
@property (nonatomic) long long numUniqueAnchorOccurrencesWithUniqueCandidateOccurrence;
@property (nonatomic) double posteriorProbability;

- (void).cxx_destruct;
- (id)candidateId;
- (double)classConditionalProbability;
- (id)description;
- (id)launchHistory;
- (long long)numUniqueAnchorOccurrencesWithUniqueCandidateOccurrence;
- (double)posteriorProbability;
- (void)setCandidateId:(id)arg1;
- (void)setClassConditionalProbability:(double)arg1;
- (void)setLaunchHistory:(id)arg1;
- (void)setNumUniqueAnchorOccurrencesWithUniqueCandidateOccurrence:(long long)arg1;
- (void)setPosteriorProbability:(double)arg1;

@end
