//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SAObjects/SABaseClientBoundCommand.h>

@class NSNumber;

@interface SASConfirmEndpoint : SABaseClientBoundCommand
{
}

+ (id)confirmEndpointWithDictionary:(id)arg1 context:(id)arg2;
+ (id)confirmEndpoint;
- (BOOL)requiresResponse;
@property(copy, nonatomic) NSNumber *endpointConfirmationTimestamp;
- (id)encodedClassName;
- (id)groupIdentifier;

@end

