//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMDaemonCore/NSObject-Protocol.h>

@class IMDCKSyncState;

@protocol IMDCKSyncStateDelegate <NSObject>

@optional
- (void)syncStateDidUpdate:(IMDCKSyncState *)arg1;
- (void)syncStateWillUpdate:(IMDCKSyncState *)arg1;
@end

