/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CMCapture.framework/CMCapture
 */

@interface BWStillImageProcessorInput : NSObject {
    BWStillImageCaptureStreamSettings * _captureStreamSettings;
    NSMutableDictionary * _outputSampleBufferRoutersByBufferType;
    BWStillImageSettings * _settings;
}

@property (nonatomic, readonly) BWStillImageCaptureSettings *captureSettings;
@property (nonatomic, readonly) BWStillImageCaptureStreamSettings *captureStreamSettings;
@property (nonatomic, readonly) bool isMaster;
@property (nonatomic, readonly) NSString *portType;
@property (nonatomic, readonly) BWStillImageProcessingSettings *processingSettings;
@property (nonatomic, readonly) FigCaptureStillImageSettings *settings;
@property (nonatomic, readonly) BWStillImageSettings *stillImageSettings;

- (void)addBypassedProcessorType:(unsigned long long)arg1 forBufferTypes:(id)arg2;
- (void)addOutputSampleBufferRouter:(id /* block */)arg1 forBufferTypes:(id)arg2;
- (id)captureSettings;
- (id)captureStreamSettings;
- (void)dealloc;
- (id)description;
- (id)initWithSettings:(id)arg1 portType:(id)arg2;
- (bool)isMaster;
- (id)outputSampleBufferRouterForBufferType:(unsigned long long)arg1;
- (id)portType;
- (id)processingSettings;
- (id)settings;
- (id)stillImageSettings;

@end
