/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIContextLayerHostView : _UISceneLayerHostView

@property (nonatomic) unsigned long long renderingMode;

+ (Class)layerClass;

- (id)initWithSceneLayer:(id)arg1;
- (id)layer;
- (unsigned long long)renderingMode;
- (void)setRenderingMode:(unsigned long long)arg1;

@end
