/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UICollectionEstimatedSolutionBookmark : NSObject {
    struct _NSRange { 
        unsigned long long location; 
        unsigned long long length; 
    }  _itemRange;
    _UICollectionLayoutItemSolver * _solution;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  _solutionFrame;
    <_UICollectionLayoutAuxillaryOffsets> * _supplementaryOffsets;
}

@property (nonatomic, readonly) struct _NSRange { unsigned long long x1; unsigned long long x2; } itemRange;
@property (nonatomic, readonly) _UICollectionLayoutItemSolver *solution;
@property (nonatomic, readonly) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } solutionFrame;
@property (nonatomic, readonly) <_UICollectionLayoutAuxillaryOffsets> *supplementaryOffsets;

- (void).cxx_destruct;
- (id)_supplementaryOffsetsForItemRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg1 solution:(id)arg2 supplementaryOffsets:(id)arg3;
- (id)description;
- (id)initWithSolution:(id)arg1 frame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg2 itemIndexOffset:(long long)arg3 supplementaryOffsets:(id)arg4 maxItemFrameCount:(long long)arg5;
- (struct _NSRange { unsigned long long x1; unsigned long long x2; })itemRange;
- (id)solution;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })solutionFrame;
- (id)supplementaryOffsets;

@end
