/* Generated by RuntimeBrowser.
 */

@protocol PNPWizardViewDelegate

@required

- (UIColor *)backgroundColorForWizardController:(PNPWizardViewController *)arg1;
- (long long)deviceType;
- (bool)shouldShowWhatsNewController;
- (void)wizardViewRequestsDismiss:(PNPWizardViewController *)arg1;

@end
