//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FinderKit/FI_TPropertyColumnPreviewDateTextFieldController.h>

__attribute__((visibility("hidden")))
@interface FI_TPropertyColumnPreviewLastOpenedDateController : FI_TPropertyColumnPreviewDateTextFieldController
{
    _Bool _alwaysShow;
}

@property(nonatomic) _Bool alwaysShow; // @synthesize alwaysShow=_alwaysShow;
- (_Bool)hasValue;
- (_Bool)shouldFetchWhenDisabled;
- (_Bool)shouldBeVisible;
- (void)initCommon;

@end

