/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

@interface PLPhotosHighlightGenerator : NSObject {
    <PLMomentGenerationDataManagement><PLHighlightItemModelReader> * _dataManager;
    PLDateRangeTitleGenerator * _dateRangeTitleGenerator;
    bool  _didCallBeginGeneration;
    PLHighlightHierarchy * _entitiesToUpdate;
    PLFrequentLocationManager * _frequentLocationManager;
    NSMutableSet * _highlightsNeedingNewKeyAsset;
    NSMutableSet * _highlightsToDelete;
    NSMutableSet * _highlightsWithDeletedAssets;
    PLLocalCreationDateCreator * _localCreationDateCreator;
    NSDateInterval * _recentHighlightsDateInterval;
    NSMutableSet * _upsertedHighlights;
}

@property (nonatomic) <PLMomentGenerationDataManagement><PLHighlightItemModelReader> *dataManager;
@property (nonatomic, readonly) PLDateRangeTitleGenerator *dateRangeTitleGenerator;
@property (nonatomic) bool didCallBeginGeneration;
@property (nonatomic, retain) PLHighlightHierarchy *entitiesToUpdate;
@property (nonatomic, readonly) PLFrequentLocationManager *frequentLocationManager;
@property (nonatomic, readonly) PLPhotosHighlightClusterGenerator *highlightClusterGenerator;
@property (nonatomic, retain) NSMutableSet *highlightsNeedingNewKeyAsset;
@property (nonatomic, retain) NSMutableSet *highlightsToDelete;
@property (nonatomic, retain) NSMutableSet *highlightsWithDeletedAssets;
@property (nonatomic, readonly) PLLocalCreationDateCreator *localCreationDateCreator;
@property (nonatomic, readonly) NSDateInterval *recentHighlightsDateInterval;
@property (nonatomic, retain) NSMutableSet *upsertedHighlights;

+ (id)_bestAssetInAssets:(id)arg1 fallback:(bool)arg2;
+ (id)_provisionalKeyAssetForDayGroupHighlight:(id)arg1;
+ (id)_provisionalKeyAssetForDayHighlight:(id)arg1;
+ (id)_provisionalKeyAssetForMonthAndYearHighlight:(id)arg1;
+ (bool)_shouldUpdateKeyAssetForParentHighlight:(id)arg1 withKeyAssetObjectID:(id)arg2;
+ (void)_updateParentHighlighNeedingNewKeyAsset:(id)arg1 withProvisionalKeyAsset:(id)arg2 updatedHighlights:(id)arg3;
+ (bool)assetEligibleForCuration:(id)arg1;
+ (bool)assetEligibleForRecents:(id)arg1;
+ (double)curationScoreForAsset:(id)arg1;
+ (void)initialize;
+ (id)provisionalKeyAssetForHighlight:(id)arg1;
+ (void)updateKeyAssetForHighlights:(id)arg1;
+ (void)updateTitleForHighlights:(id)arg1 forKind:(unsigned short)arg2 forceUpdateLocale:(bool)arg3 dateRangeTitleGenerator:(id)arg4;
+ (id)userDefaults;

- (void).cxx_destruct;
- (id)_collectMomentsRequiringReprocessingFromMoments:(id)arg1 withAllMoments:(id)arg2;
- (void)_consumeHighlightItemListChanges:(id)arg1 forKind:(unsigned short)arg2 rule:(id)arg3 resultBlock:(id /* block */)arg4;
- (id)_fetchAllMoments;
- (id)_fetchMomentsRequiringLocationProcessingWhenFrequentLocationsChanged;
- (id)_fetchMomentsWithLocationTypeUnprocessed;
- (id)_highlightMomentClustersForMoments:(id)arg1 excludingMomentIds:(id)arg2;
- (id)_highlightToReuseForMoments:(id)arg1;
- (bool)_highlightTypeSupportsVisibilityStateDayOnly:(unsigned short)arg1;
- (id)_insertDayGroupPhotosHighlightCluster:(id)arg1;
- (void)_insertDayPhotosHighlightCluster:(id)arg1;
- (id)_lastHighlightTitlesUpdateDay;
- (void)_resetProperties;
- (void)_setLastHighlightTitlesUpdateDay:(id)arg1;
- (id)_titleForAggregationDayGroupHighlight:(id)arg1;
- (void)_updateDayGroupHighlight:(id)arg1 withNewAssets:(id)arg2;
- (void)_updateDayHighlight:(id)arg1 withNewAssets:(id)arg2;
- (bool)_updateHighlightProperties:(id)arg1 fromHighlightCluster:(id)arg2;
- (void)beginGenerationWithAssets:(id)arg1 hiddenAssets:(id)arg2;
- (void)cleanupEmptyHighlights;
- (id)dataManager;
- (id)dateRangeTitleGenerator;
- (bool)didCallBeginGeneration;
- (id)entitiesToUpdate;
- (id)fetchAllOngoingTripDayGroupHighlights;
- (id)fetchAllRecentHighlights;
- (void)finishGeneration;
- (id)frequentLocationManager;
- (void)generateHighlightListForUpdatedHighlights:(id)arg1 deletedHighlights:(id)arg2;
- (void)generateHighlightsForUpsertedMoments:(id)arg1 frequentLocationsDidChange:(bool)arg2;
- (id)highlightClusterGenerator;
- (id)highlightsNeedingNewKeyAsset;
- (id)highlightsToDelete;
- (id)highlightsWithDeletedAssets;
- (id)initWithDataManager:(id)arg1 frequentLocationManager:(id)arg2 localCreationDateCreator:(id)arg3;
- (id)localCreationDateCreator;
- (void)processRecentHighlights;
- (void)processUnprocessedMomentLocations;
- (id)recentHighlightsDateInterval;
- (void)registerHighlightsWithDeletedMoments:(id)arg1;
- (void)resetDayGroupCurationForAsset:(id)arg1;
- (void)resetPreviousRecentHighlightCurationForHighlight:(id)arg1;
- (void)setDataManager:(id)arg1;
- (bool)setDefaultVisibilityStateForHighlight:(id)arg1 withHighlightCluster:(id)arg2;
- (void)setDidCallBeginGeneration:(bool)arg1;
- (void)setEntitiesToUpdate:(id)arg1;
- (void)setHighlightsNeedingNewKeyAsset:(id)arg1;
- (void)setHighlightsToDelete:(id)arg1;
- (void)setHighlightsWithDeletedAssets:(id)arg1;
- (void)setUpsertedHighlights:(id)arg1;
- (void)updateCurationForHighlight:(id)arg1 withAssetsBelongingToCuration:(id)arg2;
- (id)updateElectedEventForUpdatedMonths:(id)arg1;
- (void)updateHighlightNeedingNewKeyAssetsWithAsset:(id)arg1;
- (void)updateHighlightTitles;
- (void)updateRecentHighlightCurationForHighlight:(id)arg1;
- (id)upsertedHighlights;

@end
