/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaRemote.framework/MediaRemote
 */

@interface _MRTextInputMessageProtobuf : PBCodable <NSCopying> {
    int  _actionType;
    struct { 
        unsigned int timestamp : 1; 
        unsigned int actionType : 1; 
    }  _has;
    NSString * _text;
    double  _timestamp;
}

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (bool)readFrom:(id)arg1;
- (void)writeTo:(id)arg1;

@end
