/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
 */

@interface PKMobileAssetManager : NSObject {
    NSObject<OS_dispatch_queue> * _queue;
}

+ (id)sharedInstance;

- (void).cxx_destruct;
- (id)_compatibleVersionsWithMinimumVersion:(unsigned long long)arg1 maximumVersion:(unsigned long long)arg2;
- (void)_downloadAsset:(id)arg1 userInitiated:(bool)arg2 timeout:(long long)arg3 completion:(id /* block */)arg4;
- (id)_downloadOptionsWithUserInitiation:(bool)arg1 timeout:(long long)arg2;
- (void)_executeQueries:(id)arg1 currentIndex:(unsigned long long)arg2 userInitiated:(bool)arg3 sortDescriptors:(id)arg4 timeout:(long long)arg5 completion:(id /* block */)arg6;
- (id)_queriesForCityCodeStationProvider:(id)arg1;
- (id)_queriesForEducationVideo;
- (id)_queriesForMarketIdentifer:(id)arg1;
- (void)_retrieveAssetWithQueries:(id)arg1 latestCompatibilityVersion:(unsigned long long)arg2 userInitiated:(bool)arg3 sortDescriptors:(id)arg4 timeout:(unsigned long long)arg5 catalogExpirationDays:(long long)arg6 completionHandler:(id /* block */)arg7;
- (id)_sortDescriptorWithPreferredFeatureKey:(id)arg1 isFeaturePreferred:(bool)arg2 keyPath:(id)arg3;
- (void)fetchAssetsForMarketWithIdentifier:(id)arg1 userInitiated:(bool)arg2 completionHandler:(id /* block */)arg3;
- (void)fetchCityStationProviderAssetForBaseProvider:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)fetchEducationVideoWithPreferredFeatures:(unsigned long long)arg1 completionHandler:(id /* block */)arg2;
- (void)fetchNeededAssetsForThisDeviceWithPreferredFeatures:(unsigned long long)arg1;
- (id)init;
- (id)sortDescriptorsForCityCode;
- (id)sortDescriptorsForEducationVideoWithPreferredFeatures:(unsigned long long)arg1;
- (id)sortDescriptorsForMarkets;

@end
