/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface EBWorkbook : NSObject

+ (struct ChVector<OcText> { struct OcText {} *x1; struct OcText {} *x2; struct __compressed_pair<OcText *, ChAllocator<OcText> > { struct OcText {} *x_3_1_1; } x3; }*)createSheetNamesFromWorkbook:(id)arg1;
+ (void)readDocumentPresentation:(id)arg1 state:(id)arg2;
+ (void)readDocumentProperties:(id)arg1 state:(id)arg2;
+ (id)readWithState:(id)arg1 reader:(id)arg2;
+ (void)setupProcessors:(id)arg1;
+ (int)xlSheetTypeEnumFromEDSheet:(id)arg1;

@end
