/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AirPlayReceiver.framework/AirPlayReceiver
 */

@interface AirPlayReceiverMediaRemoteHelper : NSObject {
    NSObject<OS_dispatch_queue> * _dataTransferQueue;
    NSObject<OS_dispatch_queue> * _delegateQueue;
    void * _mediaRemoteCommandHandlerToken;
    void * _mediaRemotePlayer;
    void * _mediaRemotePlayerPathRef;
    struct OpaqueFigCFWeakReferenceHolder { } * _weakDelegate;
}

+ (void)becomeNowPlayingApplication;
+ (void)resignAsNowPlayingApplication;
+ (void)setIsNowPlayingApplication:(unsigned char)arg1;

- (void)dealloc;
- (unsigned int)handleMediaRemoteCommand:(unsigned int)arg1 withOptions:(struct __CFDictionary { }*)arg2;
- (id)initWithPlayerID:(struct __CFString { }*)arg1;
- (void)makeNowPlayingPlayer;
- (void)registerCommandHandler;
- (void)removeNowPlayingArtwork;
- (void)setAPNowPlayingInfo:(struct __CFDictionary { }*)arg1;
- (void)setDelegate:(id)arg1;
- (void)setMRNowPlayingClient:(struct __CFData { }*)arg1;
- (void)setMRNowPlayingInfo:(struct __CFDictionary { }*)arg1 withMergePolicy:(unsigned char)arg2;
- (void)setMRPlaybackState:(unsigned int)arg1;
- (void)setMRSupportedCommands:(struct __CFArray { }*)arg1;
- (void)setMRSupportedCommandsFromSerializedArray:(struct __CFArray { }*)arg1;
- (void)unregisterCommandHandler;

@end
