//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AssetCacheServicesExtensions/AssetCacheAlert.h>

@class NSString;

@interface AssetCacheUnfriendlyPeerAlert : AssetCacheAlert
{
    NSString *_peerAddress;
}

- (void).cxx_destruct;
@property(retain) NSString *peerAddress; // @synthesize peerAddress=_peerAddress;
- (id)sharingPrefsAnchor;
- (id)verboseText;
- (id)externalRepresentation;
- (id)initWithExternalRepresentation:(id)arg1;
- (id)initWithPeerAddress:(id)arg1;

@end

