//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface CHBSeries : NSObject
{
}

+ (id)chdSeriesWithState:(id)arg1;
+ (id)readFrom:(struct XlChartDataSeries *)arg1 state:(id)arg2;
+ (void)resolveSeriesStyle:(id)arg1 state:(id)arg2;
+ (void)readXlChartSeriesFormat:(struct XlChartDataSeries *)arg1 chdSeries:(id)arg2 state:(id)arg3;
+ (Class)chdSeriesClassWithState:(id)arg1;

@end

