//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface TSUFileProviderUtilities : NSObject
{
}

+ (void)bookmarkableStringFromDocumentURL:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)didUpdateAlternateContentsDocumentForDocumentAtURL:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)fetchAlternateContentsURLForDocumentURL:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)setAlternateContentsURL:(id)arg1 onDocumentURL:(id)arg2 completion:(CDUnknownBlockType)arg3;
+ (void)initialize;
- (id)init;

@end

