//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AssistantServices/NSObject-Protocol.h>

@class NSString, NSUUID;

@protocol AFAudioDeviceInfoMutating <NSObject>
- (void)setDeviceUID:(NSUUID *)arg1;
- (void)setIsRemoteDevice:(BOOL)arg1;
- (void)setRoute:(NSString *)arg1;
@end

