/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CameraEffectsKit.framework/CameraEffectsKit
 */

@interface JTFormatters : NSObject

+ (id)dateComponentsFormatterHourMinSec;
+ (id)dateComponentsFormatterMinSec;
+ (id)dateFormatter;
+ (id)dateFormatterDayOfWeekMonthDayYear;
+ (id)dateFormatterDebugDate;
+ (id)dateFormatterLongStyle;
+ (id)dateFormatterMonthDay;

@end
