/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Vision.framework/Vision
 */

@interface VNImageBuffer : NSObject <VNSequencedRequestSupporting> {
    VNImageSourceManager * _imageSourceManager;
    NSDictionary * _options;
    int  _orientation;
    struct CGImage { } * _origCGImage;
    CIImage * _origCIImage;
    unsigned long long  _origImageHeight;
    unsigned long long  _origImageWidth;
    struct __CVBuffer { } * _origPixelBuffer;
    struct opaqueCMSampleBuffer { } * _origSampleBuffer;
    CIContext * _passedInCIContext;
    struct __CFArray { } * _pixelBufferReps;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _pixelBufferRepsLock;
}

@property (readonly) unsigned long long height;
@property (readonly) struct { struct { long long x_1_1_1; int x_1_1_2; unsigned int x_1_1_3; long long x_1_1_4; } x1; struct { long long x_2_1_1; int x_2_1_2; unsigned int x_2_1_3; long long x_2_1_4; } x2; struct { long long x_3_1_1; int x_3_1_2; unsigned int x_3_1_3; long long x_3_1_4; } x3; } timingInfo;
@property (readonly) unsigned long long width;

+ (int)_VNVTImageRotationSessionCreate:(struct OpaqueVTImageRotationSession {}**)arg1 rotation:(unsigned int)arg2;
+ (int)_VNVTPixelTransferSessionCreate:(struct OpaqueVTPixelTransferSession {}**)arg1;
+ (int)_helpReadOrientationFromOptionsDictionary:(id)arg1;
+ (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })computeCenterCropRectFromCropRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 inImageSize:(struct CGSize { double x1; double x2; })arg2 calculatedScaleX:(double*)arg3 calculatedScaleY:(double*)arg4;
+ (struct CGColorSpace { }*)copyColorspaceForFormat:(unsigned int)arg1 bitmapInfo:(unsigned int*)arg2;
+ (const struct __CFDictionary { }*)ioSurfaceBackedPixelBufferAttributes;

- (void).cxx_destruct;
- (id)_baseCIImage;
- (struct __CVBuffer { }*)_baseCVPixelBuffer;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_calculateTargetRectFromCropRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (bool)_cropCIImage:(id)arg1 outBuffer:(struct __CVBuffer {}**)arg2 width:(unsigned long long)arg3 height:(unsigned long long)arg4 format:(unsigned int)arg5 cropRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg6 performCrop:(bool)arg7 options:(id)arg8 error:(id*)arg9;
- (bool)_cropCVPixelBuffer:(struct __CVBuffer { }*)arg1 outBuffer:(struct __CVBuffer {}**)arg2 width:(unsigned long long)arg3 height:(unsigned long long)arg4 format:(unsigned int)arg5 cropRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg6 performCrop:(bool)arg7 options:(id)arg8 error:(id*)arg9;
- (bool)_cropImageSourceManager:(id)arg1 outBuffer:(struct __CVBuffer {}**)arg2 width:(unsigned long long)arg3 height:(unsigned long long)arg4 format:(unsigned int)arg5 cropRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg6 performCrop:(bool)arg7 options:(id)arg8 error:(id*)arg9;
- (void)_dumpIntermediateImage:(struct __CVBuffer { }*)arg1 withOptions:(id)arg2;
- (bool)_isRectOutOfBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (id)_optionsWithOverridingOptions:(id)arg1;
- (struct __CVBuffer { }*)_retrieveBufferFromCacheIfFoundWithWidth:(unsigned long long)arg1 height:(unsigned long long)arg2 format:(unsigned int)arg3;
- (bool)_useCoreImageForFormat:(unsigned int)arg1;
- (id)augmentedBuffersWithWidth:(unsigned long long)arg1 height:(unsigned long long)arg2 format:(unsigned int)arg3 options:(id)arg4 augmentationOptions:(id)arg5 error:(id*)arg6;
- (id)augmentedCroppedBuffersWithWidth:(unsigned long long)arg1 height:(unsigned long long)arg2 format:(unsigned int)arg3 cropRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg4 options:(id)arg5 augmentationOptions:(id)arg6 error:(id*)arg7;
- (struct __CVBuffer { }*)bufferWithWidth:(unsigned long long)arg1 height:(unsigned long long)arg2 format:(unsigned int)arg3 options:(id)arg4 error:(id*)arg5;
- (void)calculateOrientationCorrectedImageDimensions;
- (struct __CVBuffer { }*)createBufferWithMaxSideLengthOf:(unsigned long long)arg1 andPixelFormat:(unsigned int)arg2 andOptions:(id)arg3 error:(id*)arg4;
- (struct __CVBuffer { }*)createCroppedBufferWithMaxSideLengthOf:(unsigned long long)arg1 andCropBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg2 andPixelFormat:(unsigned int)arg3 andOptions:(id)arg4 error:(id*)arg5;
- (struct __CVBuffer { }*)cropAndScaleBufferWithWidth:(unsigned long long)arg1 height:(unsigned long long)arg2 cropRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg3 format:(unsigned int)arg4 imageCropAndScaleOption:(unsigned long long)arg5 options:(id)arg6 error:(id*)arg7 calculatedNormalizedOriginOffset:(struct CGPoint { double x1; double x2; }*)arg8 calculatedScaleX:(double*)arg9 calculatedScaleY:(double*)arg10;
- (struct __CVBuffer { }*)croppedBufferWithWidth:(unsigned long long)arg1 height:(unsigned long long)arg2 format:(unsigned int)arg3 cropRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg4 options:(id)arg5 error:(id*)arg6;
- (void)dealloc;
- (id)fileURL;
- (bool)getCameraIntrinsicsAvailable:(struct { /* Warning: Unrecognized filer type: ']' using 'void*' */ void*x1[3]; }*)arg1;
- (bool)getCameraOpticalCenterIfAvailable:(struct CGPoint { double x1; double x2; }*)arg1;
- (bool)getPixelFocalLengthIfAvailable:(float*)arg1;
- (unsigned long long)height;
- (id)imageProperties;
- (id)initWithCGImage:(struct CGImage { }*)arg1 options:(id)arg2;
- (id)initWithCGImage:(struct CGImage { }*)arg1 orientation:(unsigned int)arg2 options:(id)arg3;
- (id)initWithCIImage:(id)arg1 options:(id)arg2;
- (id)initWithCIImage:(id)arg1 orientation:(unsigned int)arg2 options:(id)arg3;
- (id)initWithCMSampleBuffer:(struct opaqueCMSampleBuffer { }*)arg1 options:(id)arg2;
- (id)initWithCMSampleBuffer:(struct opaqueCMSampleBuffer { }*)arg1 orientation:(unsigned int)arg2 options:(id)arg3;
- (id)initWithCVPixelBuffer:(struct __CVBuffer { }*)arg1 options:(id)arg2;
- (id)initWithCVPixelBuffer:(struct __CVBuffer { }*)arg1 orientation:(unsigned int)arg2 options:(id)arg3;
- (id)initWithData:(id)arg1 options:(id)arg2;
- (id)initWithData:(id)arg1 orientation:(unsigned int)arg2 options:(id)arg3;
- (id)initWithOptions:(id)arg1 orientation:(unsigned int)arg2;
- (id)initWithURL:(id)arg1 options:(id)arg2;
- (id)initWithURL:(id)arg1 orientation:(unsigned int)arg2 options:(id)arg3;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })makeClippedRectAgainstImageExtentUsingOriginalRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (int)orientation;
- (struct CGImage { }*)originalCGImage;
- (struct __CVBuffer { }*)originalPixelBuffer;
- (bool)processInChunksOfSize:(unsigned long long)arg1 overlapFraction:(float)arg2 options:(id)arg3 roi:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg4 handler:(id /* block */)arg5 error:(id*)arg6;
- (void)purgeCachedRepresentations;
- (id)sequencedRequestPreviousObservationsKey;
- (struct { struct { long long x_1_1_1; int x_1_1_2; unsigned int x_1_1_3; long long x_1_1_4; } x1; struct { long long x_2_1_1; int x_2_1_2; unsigned int x_2_1_3; long long x_2_1_4; } x2; struct { long long x_3_1_1; int x_3_1_2; unsigned int x_3_1_3; long long x_3_1_4; } x3; })timingInfo;
- (bool)wantsSequencedRequestObservationsRecording;
- (unsigned long long)width;

@end
