/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TeaFoundation.framework/TeaFoundation
 */

@interface TeaFoundation.DeviceStorageManager : _TtCs12_SwiftObject {
    void lock;
    void observablePurgeUrgency;
    void purgeables;
}

@end
