//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MusicLibrary/ML3Client.h>

@interface ML3DaemonClient : ML3Client
{
}

+ (id)sharedDaemonClient;
- (int)processID;
- (id)name;
- (id)bundleID;
- (id)init;

@end

