//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Intents/NSObject-Protocol.h>

@class _INPBDateTime, _INPBRecurrenceValue, _INPBValueMetadata;

@protocol _INPBDateTimeRangeValue <NSObject>
@property(readonly, nonatomic) BOOL hasValueMetadata;
@property(retain, nonatomic) _INPBValueMetadata *valueMetadata;
@property(readonly, nonatomic) BOOL hasStartDateTime;
@property(retain, nonatomic) _INPBDateTime *startDateTime;
@property(nonatomic) BOOL hasStartCalendar;
@property(nonatomic) long long startCalendar;
@property(readonly, nonatomic) BOOL hasRecurrence;
@property(retain, nonatomic) _INPBRecurrenceValue *recurrence;
@property(readonly, nonatomic) BOOL hasEndDateTime;
@property(retain, nonatomic) _INPBDateTime *endDateTime;
@property(nonatomic) BOOL hasEndCalendar;
@property(nonatomic) long long endCalendar;
@property(nonatomic) BOOL hasAllDay;
@property(nonatomic) BOOL allDay;
@end

