//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Intents/NSObject-Protocol.h>

@class NSArray, _INPBTimer;

@protocol _INPBDeleteTimerIntentResponse <NSObject>
+ (Class)deletedTimersType;
@property(readonly, nonatomic) unsigned long long deletedTimersCount;
@property(copy, nonatomic) NSArray *deletedTimers;
- (_INPBTimer *)deletedTimersAtIndex:(unsigned long long)arg1;
- (void)addDeletedTimers:(_INPBTimer *)arg1;
- (void)clearDeletedTimers;
@end

