/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowKit.framework/WorkflowKit
 */

@interface WFHandleIntentAction : WFAction <WFIntentExecutorDelegate, WFStandaloneShortcutAction> {
    INCExtensionConnection * _connection;
    WFIntentExecutor * _executor;
    NSString * _localizedName;
    INIntent * _runningIntent;
    INStringLocalizer * _stringLocalizer;
}

@property (nonatomic, retain) INCExtensionConnection *connection;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) WFIntentExecutor *executor;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) long long intentCategory;
@property (nonatomic, readonly) INIntentDescription *intentDescription;
@property (nonatomic, copy) NSString *localizedName;
@property (nonatomic, readonly, copy) INIntent *runningIntent;
@property (nonatomic, readonly) NSArray *slots;
@property (nonatomic, readonly) INStringLocalizer *stringLocalizer;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)accessBundleContentWithBlock:(id /* block */)arg1;
- (bool)allowsContinueInAppWhenRunningRemotely;
- (unsigned long long)allowsInteractiveSlotResolution;
- (bool)attemptRecoveryFromError:(id)arg1 optionIndex:(unsigned long long)arg2;
- (void)cancel;
- (id)confirmationAlertForInteraction:(id)arg1 completionHandler:(id /* block */)arg2;
- (id)connection;
- (id)createResourceManager;
- (id)errorAttributedToApp:(id)arg1;
- (id)errorFromConfirmResponse:(id)arg1 intent:(id)arg2;
- (id)errorFromHandleResponse:(id)arg1 intent:(id)arg2;
- (id)errorFromResolutionResult:(id)arg1 forSlot:(id)arg2 onIntent:(id)arg3;
- (id)errorThatLaunchesApp:(id)arg1;
- (id)executor;
- (id)executorWithIntent:(id)arg1 groupIdentifier:(id)arg2;
- (void)finishRunningByContinuingInApp;
- (void)finishRunningWithError:(id)arg1;
- (void)generatePopulatedIntentFromInput:(id)arg1 processedParameters:(id)arg2 completion:(id /* block */)arg3;
- (void)generatePopulatedIntentWithIdentifier:(id)arg1 fromInput:(id)arg2 processedParameters:(id)arg3 completion:(id /* block */)arg4;
- (void)generateShortcutRepresentation:(id /* block */)arg1;
- (void)generateStandaloneShortcutRepresentation:(id /* block */)arg1;
- (id)generatedAccessResource;
- (id)generatedIntentWithIdentifier:(id)arg1 input:(id)arg2 processedParameters:(id)arg3 error:(id*)arg4;
- (id)generatedIntentWithInput:(id)arg1 processedParameters:(id)arg2 error:(id*)arg3;
- (void)getErrorFromExtensionError:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)getOutputFromIntentResponse:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)handleExecutionCompletionWithInteraction:(id)arg1 error:(id)arg2;
- (void)handleExecutorError:(id)arg1;
- (void)handleResolutionResult:(id)arg1 forSlot:(id)arg2 onIntent:(id)arg3;
- (id)initWithIdentifier:(id)arg1 definition:(id)arg2 serializedParameters:(id)arg3;
- (id)initWithIdentifier:(id)arg1 definition:(id)arg2 serializedParameters:(id)arg3 stringLocalizer:(id)arg4;
- (void)initializeParameters;
- (bool)inputPassthrough;
- (long long)intentCategory;
- (id)intentDescription;
- (void)intentExecutor:(id)arg1 showConfirmationForInteraction:(id)arg2 confirmationRequired:(bool)arg3 authenticationRequired:(bool)arg4 completionHandler:(id /* block */)arg5;
- (void)intentExecutor:(id)arg1 showConfirmationForSlot:(id)arg2 item:(id)arg3 intent:(id)arg4 completion:(id /* block */)arg5;
- (void)intentExecutorRequestsContinueInApp:(id)arg1;
- (bool)intentIsHandledBySiri:(id)arg1;
- (bool)isWorkflowInDatabase;
- (void)launchAppInBackground:(bool)arg1;
- (void)localizedConfirmationPromptForAttribute:(id)arg1 intent:(id)arg2 completion:(id /* block */)arg3;
- (void)localizedDisambiguationPromptForAttribute:(id)arg1 intent:(id)arg2 disambiguationItems:(id)arg3 completion:(id /* block */)arg4;
- (id)localizedName;
- (bool)opensInApp;
- (bool)parameterCombinationForIntentSupportsBackgroundExecution:(id)arg1;
- (id)parameterForSlot:(id)arg1;
- (void)populateIntent:(id)arg1 withInput:(id)arg2 processedParameters:(id)arg3 completionHandler:(id /* block */)arg4;
- (bool)requiresRemoteExecution;
- (bool)requiresShowsWhenRun;
- (void)resolveSlot:(id)arg1 withProcessedValue:(id)arg2 parameter:(id)arg3 input:(id)arg4 completion:(id /* block */)arg5;
- (id)rootCauseErrorFromError:(id)arg1;
- (void)runAsynchronouslyWithInput:(id)arg1;
- (bool)runInProcess;
- (id)runningIntent;
- (void)setConnection:(id)arg1;
- (void)setExecutor:(id)arg1;
- (void)setLocalizedName:(id)arg1;
- (bool)shouldDonateIntent:(id)arg1;
- (bool)shouldOpenAppThroughSiriForIntent:(id)arg1 intentResponse:(id)arg2;
- (void)showAskForValueAndRetryForSlot:(id)arg1 onIntent:(id)arg2;
- (void)showConfirmationAndRetryForSlot:(id)arg1 item:(id)arg2 onIntent:(id)arg3 completionHandler:(id /* block */)arg4;
- (void)showDisambiguationAndRetryForSlot:(id)arg1 items:(id)arg2 onIntent:(id)arg3;
- (void)showInteractionIfNeeded:(id)arg1 inUserInterface:(id)arg2 requiringConfirmation:(bool)arg3 requiringAuthentication:(bool)arg4 executionStage:(long long)arg5 completionHandler:(id /* block */)arg6;
- (bool)showsWhenRun;
- (id)showsWhenRunIfApplicable;
- (bool)skipSiriExecution;
- (bool)skipsProcessingHiddenParameters;
- (id)slots;
- (void)startExecutingIntent:(id)arg1;
- (id)stringLocalizer;
- (id)unknownErrorWithCode:(long long)arg1 localizedDescription:(id)arg2 userInfo:(id)arg3;
- (void)wasAddedToWorkflowByUser:(id)arg1;

@end
