//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface C2Route : NSObject
{
    NSString *_destination;
    double _lastUpdated;
}

- (void).cxx_destruct;
@property(nonatomic) double lastUpdated; // @synthesize lastUpdated=_lastUpdated;
@property(retain, nonatomic) NSString *destination; // @synthesize destination=_destination;

@end

