/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

@interface PLBackgroundJobEditRenderingWorker : PLBackgroundJobWorker {
    PAImageConversionServiceClient * _imageConversionServiceClient;
    NSProgress * _progressForCurrentAsset;
    PAVideoConversionServiceClient * _videoConversionServiceClient;
}

+ (id)workerWithLibrary:(id)arg1;

- (void).cxx_destruct;
- (id)_predicateToFetchDeferredAdjustmentNeededAssets;
- (void)dealloc;
- (bool)hasPendingJobs;
- (bool)isInterruptible;
- (id)managedObjectIDsNeedingProcessing;
- (void)performWorkOnManagedObjectID:(id)arg1 completion:(id /* block */)arg2;
- (void)stopWorkingOnManagedObjectID:(id)arg1;

@end
