/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

@interface PLPhotoLibraryOptions : NSObject <NSSecureCoding> {
    bool  _automaticallyMergesContext;
    unsigned long long  _libraryInitiator;
    unsigned long long  _libraryRole;
    bool  _preventsWaitingForRequiredState;
    long long  _requiredState;
}

@property (nonatomic) bool automaticallyMergesContext;
@property (nonatomic) unsigned long long libraryInitiator;
@property (nonatomic) unsigned long long libraryRole;
@property (nonatomic) bool preventsWaitingForRequiredState;
@property (nonatomic) long long requiredState;

+ (bool)supportsSecureCoding;

- (bool)automaticallyMergesContext;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (unsigned long long)libraryInitiator;
- (unsigned long long)libraryRole;
- (bool)preventsWaitingForRequiredState;
- (long long)requiredState;
- (void)setAutomaticallyMergesContext:(bool)arg1;
- (void)setLibraryInitiator:(unsigned long long)arg1;
- (void)setLibraryRole:(unsigned long long)arg1;
- (void)setPreventsWaitingForRequiredState:(bool)arg1;
- (void)setRequiredState:(long long)arg1;

@end
