/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriInference.framework/SiriInference
 */

@interface SiriInference.DateTime : _TtCs12_SwiftObject {
    void date;
    void definedValue;
    void occurringIn;
    void recurrencePattern;
    void temporalIntent;
    void time;
}

@end
