/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PersonalizationPortraitInternals.framework/PersonalizationPortraitInternals
 */

@interface PPMediaPlayerDelegate : NSObject {
    NSObject<OS_dispatch_queue> * _dispatchQueue;
    double  _donationDelaySeconds;
    PPNamedEntityStore * _namedEntityStore;
    PPMediaPlayerResponse * _pendingDonation;
    NSDate * _pendingDonationTimestamp;
    bool  _useSGNamedEntityDissector;
}

+ (id)bundleIdOfCurrentForegroundApp;

- (void).cxx_destruct;
- (void)_donateDelayedResponse:(id)arg1 timePlayed:(double)arg2 bundleId:(id)arg3;
- (void)_registerForNowPlayingNotifications;
- (id)getResponse;
- (id)init;
- (id)initWithNamedEntityStore:(id)arg1 donationDelaySeconds:(double)arg2 registersResponseLoading:(bool)arg3 useSGNamedEntityDissector:(bool)arg4;
- (void)processResponse:(id)arg1;
- (void)waitForQueueEmpty;

@end
