//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <ContactsAutocomplete/CNAutocompleteSourceInclusionPolicy-Protocol.h>

@class CNUserDefaults, NSString;

@interface _CNAutocompleteUserDefaultsSourceInclusionPolicy : NSObject <CNAutocompleteSourceInclusionPolicy>
{
    CNUserDefaults *_userDefaults;
}

- (void).cxx_destruct;
@property(readonly) CNUserDefaults *userDefaults; // @synthesize userDefaults=_userDefaults;
@property(readonly) BOOL includeSupplementalResults;
@property(readonly) BOOL includeCalendarServers;
@property(readonly) BOOL includeDirectoryServers;
@property(readonly) BOOL includePredictions;
@property(readonly) BOOL includeLocalExtensions;
@property(readonly) BOOL includeSuggestions;
@property(readonly) BOOL includeRecents;
@property(readonly) BOOL includeContacts;
- (id)initWithUserDefaults:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

