/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ProxCardKit.framework/ProxCardKit
 */

@interface PRXPickerView : UIPickerView

- (struct CGSize { double x1; double x2; })intrinsicContentSize;

@end
