/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SampleAnalysis.framework/SampleAnalysis
 */

@interface SADispatchQueueState : NSObject <SASerializable> {
    SAThread * _thread;
    unsigned long long  _threadStateIndex;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly) SAThread *thread;
@property (readonly) SAThreadState *threadState;
@property unsigned long long threadStateIndex;

+ (id)classDictionaryKey;
+ (id)newInstanceWithoutReferencesFromSerializedBuffer:(const struct { unsigned char x1; unsigned char x2; unsigned long long x3; unsigned int x4; }*)arg1 bufferLength:(unsigned long long)arg2;
+ (id)stateWithThread:(id)arg1 threadStateIndex:(unsigned long long)arg2;

- (void).cxx_destruct;
- (bool)addSelfToBuffer:(struct { unsigned char x1; unsigned char x2; unsigned long long x3; unsigned int x4; }*)arg1 bufferLength:(unsigned long long)arg2 withCompletedSerializationDictionary:(id)arg3;
- (void)addSelfToSerializationDictionary:(id)arg1;
- (id)debugDescriptionWithDispatchQueue:(id)arg1;
- (id)initWithThread:(id)arg1 threadStateIndex:(unsigned long long)arg2;
- (void)populateReferencesUsingBuffer:(const struct { unsigned char x1; unsigned char x2; unsigned long long x3; unsigned int x4; }*)arg1 bufferLength:(unsigned long long)arg2 andDeserializationDictionary:(id)arg3 andDataBufferDictionary:(id)arg4;
- (void)setThreadStateIndex:(unsigned long long)arg1;
- (unsigned long long)sizeInBytesForSerializedVersion;
- (id)thread;
- (id)threadState;
- (unsigned long long)threadStateIndex;

@end
