//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <StoreFoundation/ISOperation.h>

@class NSNumber, NSURL;

@interface ISFetchIconOperation : ISOperation
{
    NSURL *_remoteURL;
    NSURL *_localURL;
    NSURL *_localIconURL;
    NSNumber *_productID;
}

- (void).cxx_destruct;
@property(readonly) NSNumber *productID; // @synthesize productID=_productID;
@property(readonly) NSURL *iconURL; // @synthesize iconURL=_localIconURL;
- (void)run;
- (id)initWithProductID:(id)arg1 url:(id)arg2 storeClient:(id)arg3;

@end

