//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CoreSuggestionsUI/NSObject-Protocol.h>

@class NSViewController, SGSuggestionPresenter;

@protocol SGSuggestionPresenterDelegate <NSObject>
- (void)suggestionPresenterWantsToHideBanner:(SGSuggestionPresenter *)arg1;
- (void)suggestionPresenterWantsToShowBanner:(SGSuggestionPresenter *)arg1;

@optional
- (long long (^)(id, id))suggestionCategoryComparatorForManager:(SGSuggestionPresenter *)arg1;
- (void)suggestionPresenter:(SGSuggestionPresenter *)arg1 didDismissViewController:(NSViewController *)arg2;
- (void)suggestionPresenter:(SGSuggestionPresenter *)arg1 willDismissViewController:(NSViewController *)arg2;
- (void)suggestionPresenter:(SGSuggestionPresenter *)arg1 didPresentViewController:(NSViewController *)arg2;
- (void)suggestionPresenter:(SGSuggestionPresenter *)arg1 willPresentViewController:(NSViewController *)arg2;
@end

