//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CoreSuggestionsUI/NSObject-Protocol.h>

@class SGRealtimeContact, SGUISuggestedContactPopoverViewController;

@protocol SuggestedContactPopoverControllerDelegate <NSObject>
- (void)contactPopoverController:(SGUISuggestedContactPopoverViewController *)arg1 didCommitSuggestedContact:(SGRealtimeContact *)arg2;
- (void)contactPopoverController:(SGUISuggestedContactPopoverViewController *)arg1 didIgnoreSuggestedContact:(SGRealtimeContact *)arg2;
@end

