//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSPressGestureRecognizer.h>

__attribute__((visibility("hidden")))
@interface _MKAnnotationDragGestureRecognizer : NSPressGestureRecognizer
{
    struct CGPoint _dragLocation;
    BOOL _hasCustomDragLocation;
}

- (struct CGPoint)locationInView:(id)arg1;
- (void)reset;
- (void)mouseDragged:(id)arg1;
- (double)allowableMovement;

@end

