//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, _MXVersion;

__attribute__((visibility("hidden")))
@interface _MXBundleBlacklistEntry : NSObject
{
    NSString *_bundleIdentifier;
    _MXVersion *_minimum;
    _MXVersion *_maximum;
}

+ (id)blacklistEntriesFromDefaultsValue:(id)arg1;
- (void).cxx_destruct;
- (BOOL)isExtensionAllowed:(id)arg1;
- (BOOL)isBundleProxyAllowed:(id)arg1;
- (BOOL)_isVersionValueAllowed:(id)arg1;
- (id)initWithBundleIdentifier:(id)arg1 minimumDisallowedVersion:(id)arg2 maximumDisallowedVersion:(id)arg3;

@end

