//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MapKit/MKPlaceHoursViewController.h>

__attribute__((visibility("hidden")))
@interface MKPlaceMessageHoursViewController : MKPlaceHoursViewController
{
}

+ (id)messsageHoursWithMapItem:(id)arg1;
- (id)hoursBuilderWithHours:(id)arg1;
- (id)timeZone;
- (id)businessHours;
- (id)titleString;
- (BOOL)_canShowWhileLocked;

@end

