//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MapKit/MKCustomSeparatorTableViewCell.h>

@class NSProgressIndicator, _MKUILabel;

__attribute__((visibility("hidden")))
@interface MKTransitLoadingTableViewCell : MKCustomSeparatorTableViewCell
{
    _MKUILabel *_loadingLabel;
    NSProgressIndicator *_loadingIndicator;
}

- (void).cxx_destruct;
- (void)stopAnimating;
- (void)startAnimating;
- (void)dealloc;
- (id)initWithReuseIdentifier:(id)arg1;

@end

