//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpriteKit/SKAction.h>

__attribute__((visibility("hidden")))
@interface SKJavaScriptAction : SKAction
{
}

+ (id)javaScriptActionWithDuration:(double)arg1 script:(id)arg2;

@end

