/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Metal.framework/Metal
 */

@interface MTLCommandQueueDescriptorInternal : MTLCommandQueueDescriptor {
    NSObject<OS_dispatch_queue> * _commitQueue;
    bool  _commitSynchronously;
    NSObject<OS_dispatch_queue> * _completionQueue;
    unsigned long long  _devicePartition;
    bool  _disableCrossQueueHazardTracking;
    unsigned long long  _maxCommandBufferCount;
    bool  _openGLQueue;
    unsigned long long  _qosLevel;
}

@property bool isOpenGLQueue;

- (id)commitQueue;
- (bool)commitSynchronously;
- (id)completionQueue;
- (id)description;
- (unsigned long long)devicePartition;
- (bool)disableCrossQueueHazardTracking;
- (id)formattedDescription:(unsigned long long)arg1;
- (id)init;
- (bool)isOpenGLQueue;
- (unsigned long long)maxCommandBufferCount;
- (unsigned long long)qosLevel;
- (void)setCommitQueue:(id)arg1;
- (void)setCommitSynchronously:(bool)arg1;
- (void)setCompletionQueue:(id)arg1;
- (void)setDevicePartition:(unsigned long long)arg1;
- (void)setDisableCrossQueueHazardTracking:(bool)arg1;
- (void)setIsOpenGLQueue:(bool)arg1;
- (void)setMaxCommandBufferCount:(unsigned long long)arg1;
- (void)setQosLevel:(unsigned long long)arg1;

@end
