/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NetworkRelay.framework/NetworkRelay
 */

@interface NRDevicePreferences : NSObject {
    NSObject<OS_xpc_object> * _connection;
    NRDeviceIdentifier * _deviceIdentifier;
    unsigned long long  _identifier;
    NRBluetoothLinkPreferences * _internalBluetoothLinkPreferences;
    bool  _internalDeviceSetupCompleted;
    bool  _internalDeviceSetupStarted;
    NSSet * _internalPolicyTrafficClassifiers;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _lock;
    unsigned long long  _preferWiFiRequestCount;
    NRDevicePreferencesQuickRelay * _quickRelayPreference;
    unsigned long long  _quickRelayRequestCount;
}

@property (nonatomic, retain) NRBluetoothLinkPreferences *bluetoothLinkPreferences;
@property (nonatomic, retain) NSObject<OS_xpc_object> *connection;
@property (nonatomic, retain) NRDeviceIdentifier *deviceIdentifier;
@property (nonatomic, readonly) bool hasPreferWiFiRequest;
@property (nonatomic, readonly) bool hasQuickRelayRequest;
@property (nonatomic) unsigned long long identifier;
@property (nonatomic, retain) NRBluetoothLinkPreferences *internalBluetoothLinkPreferences;
@property (nonatomic) bool internalDeviceSetupCompleted;
@property (nonatomic) bool internalDeviceSetupStarted;
@property (nonatomic, retain) NSSet *internalPolicyTrafficClassifiers;
@property (nonatomic) struct os_unfair_lock_s { unsigned int x1; } lock;
@property (nonatomic, retain) NSSet *policyTrafficClassifiers;
@property (nonatomic) unsigned long long preferWiFiRequestCount;
@property (nonatomic, retain) NRDevicePreferencesQuickRelay *quickRelayPreference;
@property (nonatomic) unsigned long long quickRelayRequestCount;

- (void).cxx_destruct;
- (void)addPreferWiFiRequest;
- (void)addQuickRelayRequest;
- (id)bluetoothLinkPreferences;
- (void)cancel;
- (void)cancelConnectionLocked;
- (id)connection;
- (id)copyDetailsLocked;
- (void)dealloc;
- (id)description;
- (id)deviceIdentifier;
- (void)deviceSetupCompleted;
- (void)deviceSetupStarted;
- (bool)hasPreferWiFiRequest;
- (bool)hasPreferencesToSendLocked;
- (bool)hasQuickRelayRequest;
- (unsigned long long)identifier;
- (id)initWithDeviceIdentifier:(id)arg1;
- (id)internalBluetoothLinkPreferences;
- (bool)internalDeviceSetupCompleted;
- (bool)internalDeviceSetupStarted;
- (id)internalPolicyTrafficClassifiers;
- (struct os_unfair_lock_s { unsigned int x1; })lock;
- (id)policyTrafficClassifiers;
- (unsigned long long)preferWiFiRequestCount;
- (id)quickRelayPreference;
- (unsigned long long)quickRelayRequestCount;
- (void)removeAllQuickRelayRequests;
- (void)removePreferWiFiRequest;
- (void)removePreferWiFiRequestLocked;
- (void)removeQuickRelayRequest;
- (void)removeQuickRelayRequestLocked:(bool)arg1;
- (void)restartConnectionLocked;
- (void)sendDevicePreferencesLocked;
- (void)setBluetoothLinkPreferences:(id)arg1;
- (void)setConnection:(id)arg1;
- (void)setDeviceIdentifier:(id)arg1;
- (void)setIdentifier:(unsigned long long)arg1;
- (void)setInternalBluetoothLinkPreferences:(id)arg1;
- (void)setInternalDeviceSetupCompleted:(bool)arg1;
- (void)setInternalDeviceSetupStarted:(bool)arg1;
- (void)setInternalPolicyTrafficClassifiers:(id)arg1;
- (void)setLock:(struct os_unfair_lock_s { unsigned int x1; })arg1;
- (void)setPolicyTrafficClassifiers:(id)arg1;
- (void)setPreferWiFiRequestCount:(unsigned long long)arg1;
- (void)setQuickRelayPreference:(id)arg1;
- (void)setQuickRelayRequestCount:(unsigned long long)arg1;

@end
