/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TeaUI.framework/TeaUI
 */

@interface _TtC5TeaUIP33_2088E17F5F01413CA71FFC03BB03F42919ImageCacheOperation : NSOperation {
    void canceled;
    void downloader;
    void error;
    void image;
    void imageCompletionBlock;
    void processor;
    void request;
    void underlyingCache;
}

- (void).cxx_destruct;
- (id)init;
- (void)main;

@end
