/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOPDJoeColor : PBCodable <NSCopying> {
    NSString * _backgroundColor;
    struct { 
        unsigned int read_unknownFields : 1; 
        unsigned int read_backgroundColor : 1; 
        unsigned int read_primaryTextColor : 1; 
        unsigned int read_quaternaryTextColor : 1; 
        unsigned int read_secondaryTextColor : 1; 
        unsigned int read_tertiaryTextColor : 1; 
        unsigned int wrote_anyField : 1; 
    }  _flags;
    NSString * _primaryTextColor;
    NSString * _quaternaryTextColor;
    PBDataReader * _reader;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _readerLock;
    unsigned int  _readerMarkLength;
    unsigned int  _readerMarkPos;
    NSString * _secondaryTextColor;
    NSString * _tertiaryTextColor;
    PBUnknownFields * _unknownFields;
}

@property (nonatomic, retain) NSString *backgroundColor;
@property (nonatomic, readonly) bool hasBackgroundColor;
@property (nonatomic, readonly) bool hasPrimaryTextColor;
@property (nonatomic, readonly) bool hasQuaternaryTextColor;
@property (nonatomic, readonly) bool hasSecondaryTextColor;
@property (nonatomic, readonly) bool hasTertiaryTextColor;
@property (nonatomic, retain) NSString *primaryTextColor;
@property (nonatomic, retain) NSString *quaternaryTextColor;
@property (nonatomic, retain) NSString *secondaryTextColor;
@property (nonatomic, retain) NSString *tertiaryTextColor;
@property (nonatomic, readonly) PBUnknownFields *unknownFields;

+ (bool)isValid:(id)arg1;

- (void).cxx_destruct;
- (id)backgroundColor;
- (void)clearUnknownFields:(bool)arg1;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (bool)hasBackgroundColor;
- (bool)hasPrimaryTextColor;
- (bool)hasQuaternaryTextColor;
- (bool)hasSecondaryTextColor;
- (bool)hasTertiaryTextColor;
- (unsigned long long)hash;
- (id)init;
- (id)initWithData:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)jsonRepresentation;
- (void)mergeFrom:(id)arg1;
- (id)primaryTextColor;
- (id)quaternaryTextColor;
- (void)readAll:(bool)arg1;
- (bool)readFrom:(id)arg1;
- (id)secondaryTextColor;
- (void)setBackgroundColor:(id)arg1;
- (void)setPrimaryTextColor:(id)arg1;
- (void)setQuaternaryTextColor:(id)arg1;
- (void)setSecondaryTextColor:(id)arg1;
- (void)setTertiaryTextColor:(id)arg1;
- (id)tertiaryTextColor;
- (id)unknownFields;
- (void)writeTo:(id)arg1;

@end
