/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOPDNearestTransitParameters : PBCodable <NSCopying> {
    struct { 
        unsigned int has_lineMuid : 1; 
        unsigned int has_isTransitOnly : 1; 
    }  _flags;
    bool  _isTransitOnly;
    unsigned long long  _lineMuid;
    PBUnknownFields * _unknownFields;
}

@property (nonatomic) bool hasIsTransitOnly;
@property (nonatomic) bool hasLineMuid;
@property (nonatomic) bool isTransitOnly;
@property (nonatomic) unsigned long long lineMuid;
@property (nonatomic, readonly) PBUnknownFields *unknownFields;

+ (bool)isValid:(id)arg1;

- (void).cxx_destruct;
- (void)clearUnknownFields:(bool)arg1;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (bool)hasIsTransitOnly;
- (bool)hasLineMuid;
- (unsigned long long)hash;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (bool)isEqual:(id)arg1;
- (bool)isTransitOnly;
- (id)jsonRepresentation;
- (unsigned long long)lineMuid;
- (void)mergeFrom:(id)arg1;
- (void)readAll:(bool)arg1;
- (bool)readFrom:(id)arg1;
- (void)setHasIsTransitOnly:(bool)arg1;
- (void)setHasLineMuid:(bool)arg1;
- (void)setIsTransitOnly:(bool)arg1;
- (void)setLineMuid:(unsigned long long)arg1;
- (id)unknownFields;
- (void)writeTo:(id)arg1;

@end
