/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CFNetwork.framework/CFNetwork
 */

@interface NWStreamPair : __CFNCoreLoggable {
    unsigned char  _atEOF;
    struct __CFArray { } * _cachedPeerCerts;
    struct __CFData { } * _cachedPeerName;
    struct __SecTrust { } * _cachedTrust;
    NSObject<OS_nw_connection> * _connection;
    unsigned char  _doneInitialRead;
    long long  _outstandingWrites;
    NSObject<OS_dispatch_queue> * _queue;
    struct ReadBuffer { int (**x1)(); long long x2; id x3; long long x4; unsigned char x5; } * _readData;
    struct __CFError { } * _readError;
    struct PerSide_CFReadStream { int (**x1)(); id x2; char *x3; struct __CFReadStream {} *x4; unsigned long long x5; id x6; } * _rs;
    unsigned char  _rsClosing;
    struct __CFError { } * _writeError;
    struct PerSide_CFWriteStream { int (**x1)(); id x2; char *x3; struct __CFWriteStream {} *x4; unsigned long long x5; long long x6; id x7; } * _ws;
    unsigned char  _wsClosing;
}

- (void)dealloc;

@end
