/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/EmailFoundation.framework/EmailFoundation
 */

@interface EFSQLObjectPropertyMapper : NSObject <EFObjectPropertyMapper> {
    NSArray * _additionalColumns;
    <EFSQLValueExpressable> * _bitExpression;
    NSDictionary * _children;
    <EFSQLValueExpressable> * _condition;
    bool  _isPlaceholder;
    EFSQLColumnSchema * _sourceColumn;
    EFSQLTableSchema * _table;
}

@property (nonatomic, readonly) NSArray *additionalColumns;
@property (nonatomic, readonly) <EFSQLValueExpressable> *bitExpression;
@property (nonatomic, copy) NSDictionary *children;
@property (nonatomic, readonly) <EFSQLValueExpressable> *condition;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) bool isPlaceholder;
@property (nonatomic, readonly) EFSQLColumnSchema *sourceColumn;
@property (readonly) Class superclass;
@property (nonatomic, readonly) EFSQLTableSchema *table;

- (void).cxx_destruct;
- (id)additionalColumns;
- (id)bitExpression;
- (id)childForKey:(id)arg1;
- (id)children;
- (id)condition;
- (id)initPlaceholderMapperWithChildren:(id)arg1;
- (id)initWithChildren:(id)arg1 sourceColumn:(id)arg2;
- (id)initWithChildren:(id)arg1 sourceColumn:(id)arg2 additionalColumns:(id)arg3;
- (id)initWithChildren:(id)arg1 sourceColumn:(id)arg2 condition:(id)arg3;
- (id)initWithChildren:(id)arg1 sourceColumn:(id)arg2 condition:(id)arg3 additionalColumns:(id)arg4;
- (id)initWithChildren:(id)arg1 table:(id)arg2;
- (id)initWithChildren:(id)arg1 table:(id)arg2 additionalColumns:(id)arg3;
- (id)initWithChildren:(id)arg1 table:(id)arg2 condition:(id)arg3;
- (id)initWithChildren:(id)arg1 table:(id)arg2 condition:(id)arg3 additionalColumns:(id)arg4;
- (id)initWithColumn:(id)arg1;
- (id)initWithColumn:(id)arg1 additionalColumns:(id)arg2;
- (id)initWithColumn:(id)arg1 bitExpression:(id)arg2;
- (id)initWithColumn:(id)arg1 condition:(id)arg2;
- (id)initWithColumn:(id)arg1 condition:(id)arg2 additionalColumns:(id)arg3 bitExpression:(id)arg4;
- (bool)isPlaceholder;
- (void)setChildren:(id)arg1;
- (void)setIsPlaceholder:(bool)arg1;
- (id)sourceColumn;
- (id)table;

@end
