//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <BiometricKitUI/NSObject-Protocol.h>

@class BiometricKitEnrollProgressInfo, BiometricKitIdentity, NSData, NSDictionary;

@protocol BiometricKitDelegate <NSObject>

@optional
- (void)taskResumeStatus:(int)arg1;
- (void)templateUpdate:(BiometricKitIdentity *)arg1 withDetails:(NSDictionary *)arg2;
- (void)touchIDButtonPressed:(BOOL)arg1;
- (void)homeButtonPressed;
- (void)enrollProgress:(BiometricKitEnrollProgressInfo *)arg1;
- (void)statusMessage:(unsigned int)arg1;
- (void)matchResult:(BiometricKitIdentity *)arg1 withDetails:(NSDictionary *)arg2;
- (void)matchResult:(BiometricKitIdentity *)arg1;
- (void)enrollFeedback:(NSData *)arg1;
- (void)enrollUpdate:(NSData *)arg1;
- (void)enrollResult:(BiometricKitIdentity *)arg1;
@end

