/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NanoPreferencesSync.framework/NanoPreferencesSync
 */

@interface NPSPrefPlistProtectedUtil : NSObject

+ (bool)isPlistProtectedAtPath:(id)arg1;

@end
