//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SwiftUI/_TtC7SwiftUI18UnaryViewResponder.h>

@interface _TtC7SwiftUIP33_B437445B20C411B83F8E47EB39F0306419AnyGestureResponder : _TtC7SwiftUI18UnaryViewResponder
{
}

@end

