/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface _NSMarkupTreeNode : NSObject {
    NSMutableDictionary * _attributes;
    NSMutableArray * _children;
}

@property (nonatomic, readonly, retain) NSMutableDictionary *attributes;
@property (nonatomic, readonly, retain) NSMutableArray *children;

- (void)addAttributes:(id)arg1;
- (void)addChild:(id)arg1;
- (id)attributes;
- (id)children;
- (void)dealloc;

@end
