/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SettingsCellularUI.framework/SettingsCellularUI
 */

@interface PSUIPlanPendingTransferActivationButtonSpecifier : PSSpecifier {
    CTCellularPlanManager * _cellularPlanManager;
    CTCellularPlanPendingTransfer * _plan;
}

@property (nonatomic, retain) CTCellularPlanManager *cellularPlanManager;
@property (nonatomic, retain) CTCellularPlanPendingTransfer *plan;

- (void).cxx_destruct;
- (void)activatePlanPendingTransfer:(id)arg1;
- (id)cellularPlanManager;
- (id)initWithListController:(id)arg1 planPendingTransfer:(id)arg2;
- (id)plan;
- (void)setCellularPlanManager:(id)arg1;
- (void)setPlan:(id)arg1;
- (void)setSpecifierProperties;

@end
