/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CalendarNotification.framework/CalendarNotification
 */

@interface CALNLogSubsystem : NSObject

+ (id)alarmEngine;
+ (id)calendar;
+ (id)defaultCategory;

@end
