//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface MCPeerIDInternal : NSObject
{
    NSString *_idString;
    unsigned long long _pid64;
    NSString *_displayName;
}

@property(readonly) NSString *displayName; // @synthesize displayName=_displayName;
@property(readonly) unsigned long long pid64; // @synthesize pid64=_pid64;
@property(readonly) NSString *idString; // @synthesize idString=_idString;
- (void)dealloc;
- (id)initWithIDString:(id)arg1 pid64:(unsigned long long)arg2 displayName:(id)arg3;

@end

