//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ContentKit/DCMapsLink.h>

@class NSDictionary, NSURL;

__attribute__((visibility("hidden")))
@interface DCStandardMapsLink : DCMapsLink
{
    NSURL *_URL;
    NSDictionary *_queryDictionary;
}

+ (id)mapsLinkWithURL:(id)arg1;
+ (BOOL)isMapsURL:(id)arg1;
+ (BOOL)isStandardGoogleMapsURL:(id)arg1;
+ (BOOL)isStandardAppleMapsURL:(id)arg1;
- (void).cxx_destruct;
@property(copy, nonatomic) NSDictionary *queryDictionary; // @synthesize queryDictionary=_queryDictionary;
@property(retain, nonatomic) NSURL *URL; // @synthesize URL=_URL;
- (id)streetViewLocation;
- (BOOL)showsBicycling;
- (BOOL)showsStreetView;
- (BOOL)showsTransit;
- (BOOL)showsTraffic;
- (unsigned long long)mapType;
- (long long)zoomLevel;
- (id)centerLocation;
- (unsigned long long)directionsMode;
- (id)destinationAddress;
- (id)startAddress;
- (id)searchLocation;
- (id)searchNearQuery;
- (id)searchQuery;
- (id)initWithURL:(id)arg1;

@end

