//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSPanel.h>

@interface SHKShareWindow : NSPanel
{
    BOOL _isClosing;
}

@property BOOL isClosing; // @synthesize isClosing=_isClosing;
- (void)_close;
- (void)displayIfNeeded;
- (void)display;
- (BOOL)hidesOnDeactivate;
- (BOOL)isMovableByWindowBackground;
- (BOOL)canBecomeMainWindow;
- (BOOL)canBecomeKeyWindow;

@end

