//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GameCenterUICore/GKBrush.h>

@class GKUITheme;

@interface GKThemeBrush : GKBrush
{
    GKUITheme *_theme;
}

- (void).cxx_destruct;
@property(retain, nonatomic) GKUITheme *theme; // @synthesize theme=_theme;
- (id)initWithTheme:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

