/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/RemindersUICore.framework/RemindersUICore
 */

@interface RemindersUICore.TTRIChromelessToolbarUpdater : _TtCs12_SwiftObject {
    void contentSizeObservation;
    void deferredAction;
    void delegate;
    void scrollOffsetObserver;
    void scrollView;
}

@end
