//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <WebDriver/HTTPResponse-Protocol.h>

@class HTTPConnection, NSData;

@interface WDHTTPAsyncDataResponse : NSObject <HTTPResponse>
{
    HTTPConnection *_connection;
    NSData *_data;
    unsigned long long _readOffset;
}

- (void).cxx_destruct;
- (void)connectionDidClose;
- (BOOL)delayResponseHeaders;
- (BOOL)isAsynchronous;
- (BOOL)isDone;
- (id)readDataOfLength:(unsigned long long)arg1;
- (void)setOffset:(unsigned long long)arg1;
- (unsigned long long)offset;
- (unsigned long long)contentLength;
- (void)fulfillWithData:(id)arg1 andStartResponse:(BOOL)arg2;
- (id)initWithConnection:(id)arg1;

@end

