/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreSuggestionsML.framework/CoreSuggestionsML
 */

@interface SGQuickResponsesScoring : NSObject

+ (id)categoryScoresWithModelScores:(id)arg1 config:(id)arg2;
+ (id)modelScoresWithUnweightedScores:(id)arg1 config:(id)arg2;
+ (id)sortedWithUnweightedScores:(id)arg1 config:(id)arg2;

@end
