//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Install/IFRequirement.h>

@class IFPkg;

@interface IFInstallationCheckRequirement : IFRequirement
{
    IFPkg *_delegatePackage;
}

- (BOOL)doesEvaluateSecurely;
- (id)label;
- (BOOL)isTrueForTarget:(id)arg1;
- (id)initWithPackage:(id)arg1;

@end

