//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ACDEClient/ACMMessage.h>

#import <ACDEClient/ACMBaseAuthenticationRequest-Protocol.h>

@class NSNumber, NSString;

@interface ACMBaseAuthenticationRequestImpl : ACMMessage <ACMBaseAuthenticationRequest>
{
}


// Remaining properties
@property(retain, nonatomic) NSNumber *appID; // @dynamic appID;
@property(retain, nonatomic) NSString *appIDKey; // @dynamic appIDKey;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) NSString *realm; // @dynamic realm;
@property(retain, nonatomic) NSNumber *serverResponseTimeout; // @dynamic serverResponseTimeout;
@property(readonly) Class superclass;
@property(retain, nonatomic) NSString *userName; // @dynamic userName;
@end

