//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SAObjects/SAIntentGroupGetIntentDefinitions.h>

@interface SAIntentGroupGetIntentDefinitions (INSExtensionService)
- (BOOL)_matchesIntentDefinition:(id)arg1;
- (void)ins_getIntentDefinitionsWithCompletionHandler:(CDUnknownBlockType)arg1;
@end

