/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TestFlightCore.framework/TestFlightCore
 */

@interface TFFeedbackFormCellUpdater : NSObject

- (void)updateCell:(id)arg1 displayingEntry:(id)arg2 contentDataSource:(id)arg3 updateProxy:(id)arg4;

@end
