/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthExperienceUI.framework/HealthExperienceUI
 */

@interface HealthExperienceUI.AllHighlightCategoriesTableViewAdaptor : HealthExperienceUI.SectionedTableViewAdaptor

- (id)init;
- (bool)respondsToSelector:(SEL)arg1;

@end
