/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppleMediaServicesUIDynamic.framework/AppleMediaServicesUIDynamic
 */

@interface AppleMediaServicesUIDynamic.AMSUIDMetricsEventRecorder : _TtCs12_SwiftObject {
    void account;
    void metricsContext;
    void metricsEventRecorder;
    void overlayTopic;
}

@end
