//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSWindowController.h>

@class CWDisplayedScanResult, NSButton, NSProgressIndicator, NSString, NSTextField;

@interface CWWPSDialog_SL : NSWindowController
{
    CWDisplayedScanResult *_scanResult;
    id _delegate;
    NSString *_pin;
    BOOL _joinInProgress;
    NSTextField *windowTitleLabel;
    NSTextField *windowDescriptionLabel;
    NSButton *cancelButton;
    NSTextField *pinLabel;
    NSTextField *statusMessageLabel;
    NSButton *warningButton;
    NSProgressIndicator *progressIndicator;
    NSButton *helpButton;
}

+ (id)wpsDialogWithScanResult:(id)arg1 pin:(id)arg2;
@property(copy) NSString *pin; // @synthesize pin=_pin;
@property(copy) CWDisplayedScanResult *scanResult; // @synthesize scanResult=_scanResult;
@property id delegate; // @synthesize delegate=_delegate;
- (void)onCancelButton:(id)arg1;
- (void)onHelpButton:(id)arg1;
- (void)windowDidLoad;
- (void)close;
- (void)awakeFromNib;
- (void)clearPIN;
- (void)updatePin;
- (id)localizedStringForKey:(id)arg1;
- (id)initWithScanResult:(id)arg1 pin:(id)arg2;
- (void)dealloc;

@end

