/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ReminderKitInternal.framework/ReminderKitInternal
 */

@interface ReminderKitInternal.REMSuggestedAttributeInput : _TtCs12_SwiftObject {
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  creationDate;
    void dueDayOfWeek;
    void list;
    void location;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  reminderID;
    void title;
}

@end
