/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SleepDaemon.framework/SleepDaemon
 */

@interface HDSPSleepLockScreenAssertionManager : NSObject <HDSPEnvironmentAware, HKSPSleepLockScreenServer, NSXPCListenerDelegate> {
    NSXPCConnection * _connection;
    <HDSPSleepLockScreenAssertionManagerDelegate> * _delegate;
    HDSPEnvironment * _environment;
    NSXPCListener * _listener;
    SBSLockScreenRemoteContentAssertion * _lockScreenAssertion;
}

@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <HDSPSleepLockScreenAssertionManagerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) HDSPEnvironment *environment;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) SBSLockScreenRemoteContentAssertion *lockScreenAssertion;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)connect;
- (id)delegate;
- (void)didDismissWithReason:(long long)arg1;
- (id)environment;
- (id)initWithEnvironment:(id)arg1;
- (void)invalidateAssertion;
- (bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (id)lockScreenAssertion;
- (void)sendLockScreenState:(long long)arg1 userInfo:(id)arg2;
- (void)setDelegate:(id)arg1;
- (void)takeAssertionIfNeeded;

@end
