/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SleepDaemon.framework/SleepDaemon
 */

@interface HDSPUnitTestEnvironment : HDSPEnvironment

- (id)init;
- (bool)isDemoEnvironment;
- (void)performBlock:(id /* block */)arg1 withLock:(struct os_unfair_lock_s { unsigned int x1; }*)arg2;

@end
