//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSDateInterval.h>

@interface NSDateInterval (CRKAdditions)
- (id)crk_dateIntervalByAddingTimeInterval:(double)arg1;
@property(readonly, nonatomic) BOOL crk_containsCurrentDate;
@end

