//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface IKUser : NSObject
{
    unsigned long long _userID;
    NSString *_username;
    BOOL _subscribed;
}

@property(nonatomic, getter=isSubscribed) BOOL subscribed; // @synthesize subscribed=_subscribed;
@property(copy, nonatomic) NSString *username; // @synthesize username=_username;
@property(nonatomic) unsigned long long userID; // @synthesize userID=_userID;
- (void)dealloc;
- (id)description;
- (id)init;

@end

