//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WorkflowKit/WFAccessResource.h>

@interface WFListeningModeDeviceAccessResource : WFAccessResource
{
    unsigned long long _managerState;
    CDUnknownBlockType _availabilityCompletion;
}

+ (BOOL)isSingleton;
- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType availabilityCompletion; // @synthesize availabilityCompletion=_availabilityCompletion;
@property(nonatomic) unsigned long long managerState; // @synthesize managerState=_managerState;
- (id)localizedImportErrorReasonForGlobalLevelStatus:(unsigned long long)arg1;
- (id)localizedErrorReasonForGlobalLevelStatus:(unsigned long long)arg1;
- (id)localizedAccessResourceErrorString;
- (id)unavailableAccessResourceError;
- (unsigned long long)workflowLevelStatus;
- (unsigned long long)globalLevelStatus;
- (void)makeAvailableAtGlobalLevelWithUserInterface:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)handleNotification:(id)arg1;
- (void)dealloc;
- (void)installObserversIfNecessary;
- (id)initWithDefinition:(id)arg1;

@end

