//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WorkflowKit/WFAction.h>

#import <ActionKit/AVCapturePhotoCaptureDelegate-Protocol.h>

@class AVCaptureSession, NSString;

@interface WFTakePhotoAction : WFAction <AVCapturePhotoCaptureDelegate>
{
    unsigned long long _remainingPhotos;
    AVCaptureSession *_session;
}

- (void).cxx_destruct;
@property(retain, nonatomic) AVCaptureSession *session; // @synthesize session=_session;
@property(nonatomic) unsigned long long remainingPhotos; // @synthesize remainingPhotos=_remainingPhotos;
- (void)captureOutput:(id)arg1 didFinishProcessingPhoto:(id)arg2 error:(id)arg3;
- (void)takePhoto;
- (void)runWithAppKitUserInterface:(id)arg1 input:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

