/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ReminderMigration.framework/ReminderMigration
 */

@interface CalReminderMigrationErrorUtils : NSObject

+ (id)errorFromException:(id)arg1;

@end
