/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDCoreDuetLogEventData : NSObject {
    NSDictionary * _metadata;
    NSString * _value;
}

@property (readonly, copy) NSDictionary *metadata;
@property (readonly, copy) NSString *value;

- (void).cxx_destruct;
- (id)initWithMetadata:(id)arg1 value:(id)arg2;
- (id)metadata;
- (id)value;

@end
