//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <LinkPresentation/NSObject-Protocol.h>

@class LPLinkHTMLGenerator, LPLinkMetadata, NSData, NSString, NSURL;

@protocol LPLinkHTMLGeneratorDelegate <NSObject>

@optional
- (void)linkHTMLGenerator:(LPLinkHTMLGenerator *)arg1 didFetchMetadata:(LPLinkMetadata *)arg2;
- (NSURL *)linkHTMLGenerator:(LPLinkHTMLGenerator *)arg1 URLForResource:(NSData *)arg2 withMIMEType:(NSString *)arg3;
@end

