//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SecurityFoundation/_SFKeychainFetchResult.h>

@class SFKeychainData;

__attribute__((visibility("hidden")))
@interface SFKeychainDataFetchResult : _SFKeychainFetchResult
{
    id _dataFetchResult;
}

- (void).cxx_destruct;
- (void)fetchValueWithAuthenticationContext:(id)arg1 resultHandler:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly) SFKeychainData *value; // @dynamic value;

@end

