/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreUtils.framework/CoreUtils
 */

@interface CUSetupStepPreflightWiFi : CUSetupStep

- (bool)runAndReturnError:(id*)arg1;

@end
