/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthAlgorithms.framework/HealthAlgorithms
 */

@interface HAMenstrualAlgorithmsDayInput : NSObject {
    unsigned char  _flow;
    NSNumber * _flowUpdatedJulianDay;
    unsigned int  _julianDay;
    unsigned char  _ovulationTestResult;
    bool  _spotting;
}

@property (nonatomic) unsigned char flow;
@property (nonatomic, retain) NSNumber *flowUpdatedJulianDay;
@property (nonatomic) unsigned int julianDay;
@property (nonatomic) unsigned char ovulationTestResult;
@property (nonatomic) bool spotting;

// Image: /System/Library/PrivateFrameworks/HealthAlgorithms.framework/HealthAlgorithms

- (void).cxx_destruct;
- (unsigned char)flow;
- (id)flowUpdatedJulianDay;
- (unsigned int)julianDay;
- (unsigned char)ovulationTestResult;
- (void)setFlow:(unsigned char)arg1;
- (void)setFlowUpdatedJulianDay:(id)arg1;
- (void)setJulianDay:(unsigned int)arg1;
- (void)setOvulationTestResult:(unsigned char)arg1;
- (void)setSpotting:(bool)arg1;
- (bool)spotting;

// Image: /System/Library/PrivateFrameworks/HealthMenstrualCycles.framework/HealthMenstrualCycles

+ (id)hkmc_dayInputWithDaySummary:(id)arg1;
+ (id)hkmc_emptyDayInputWithDayIndex:(long long)arg1;

@end
