/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriInstrumentation.framework/SiriInstrumentation
 */

@interface SISchemaAudioFirstBufferRecorded : PBCodable {
    int  _audioInputRoute;
    SISchemaHardwareInterfaceIdentifier * _hardwareInterfaceVendorID;
}

@property (nonatomic) int audioInputRoute;
@property (nonatomic, retain) SISchemaHardwareInterfaceIdentifier *hardwareInterfaceVendorID;
@property (nonatomic, readonly) NSData *jsonData;

- (void).cxx_destruct;
- (int)audioInputRoute;
- (id)dictionaryRepresentation;
- (id)hardwareInterfaceVendorID;
- (unsigned long long)hash;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)jsonData;
- (bool)readFrom:(id)arg1;
- (void)setAudioInputRoute:(int)arg1;
- (void)setHardwareInterfaceVendorID:(id)arg1;
- (void)writeTo:(id)arg1;

@end
