//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <CoreCDPUI/CDPUIDeviceToDeviceEncryptionUIProvider-Protocol.h>

@interface CDPUIDeviceToDeviceEncryptionUIProviderImp : NSObject <CDPUIDeviceToDeviceEncryptionUIProvider>
{
}

- (void)_showAlertWithContext:(id)arg1 vm:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)promptIneligibilityWithContext:(id)arg1 vm:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)promptForCancelWithContext:(id)arg1 vm:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)promptForUpgradeWithContext:(id)arg1 vm:(id)arg2 completion:(CDUnknownBlockType)arg3;

@end

