/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOPDReverseGeocodingParameters : PBCodable <NSCopying> {
    NSMutableArray * _extendedLocations;
    struct { 
        unsigned int has_placeTypeLimit : 1; 
        unsigned int has_preserveOriginalLocation : 1; 
        unsigned int read_unknownFields : 1; 
        unsigned int read_extendedLocations : 1; 
        unsigned int read_locations : 1; 
        unsigned int wrote_anyField : 1; 
    }  _flags;
    NSMutableArray * _locations;
    int  _placeTypeLimit;
    bool  _preserveOriginalLocation;
    PBDataReader * _reader;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _readerLock;
    unsigned int  _readerMarkLength;
    unsigned int  _readerMarkPos;
    PBUnknownFields * _unknownFields;
}

@property (nonatomic, retain) NSMutableArray *extendedLocations;
@property (nonatomic) bool hasPlaceTypeLimit;
@property (nonatomic) bool hasPreserveOriginalLocation;
@property (nonatomic, retain) NSMutableArray *locations;
@property (nonatomic) int placeTypeLimit;
@property (nonatomic) bool preserveOriginalLocation;
@property (nonatomic, readonly) PBUnknownFields *unknownFields;

+ (Class)extendedLocationType;
+ (bool)isValid:(id)arg1;
+ (Class)locationType;

- (void).cxx_destruct;
- (int)StringAsPlaceTypeLimit:(id)arg1;
- (void)addExtendedLocation:(id)arg1;
- (void)addLocation:(id)arg1;
- (void)clearExtendedLocations;
- (void)clearLocations;
- (void)clearSensitiveFields;
- (void)clearUnknownFields:(bool)arg1;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (id)extendedLocationAtIndex:(unsigned long long)arg1;
- (id)extendedLocations;
- (unsigned long long)extendedLocationsCount;
- (bool)hasPlaceTypeLimit;
- (bool)hasPreserveOriginalLocation;
- (unsigned long long)hash;
- (id)init;
- (id)initWithData:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)jsonRepresentation;
- (id)locationAtIndex:(unsigned long long)arg1;
- (id)locations;
- (unsigned long long)locationsCount;
- (void)mergeFrom:(id)arg1;
- (int)placeTypeLimit;
- (id)placeTypeLimitAsString:(int)arg1;
- (bool)preserveOriginalLocation;
- (void)readAll:(bool)arg1;
- (bool)readFrom:(id)arg1;
- (void)setExtendedLocations:(id)arg1;
- (void)setHasPlaceTypeLimit:(bool)arg1;
- (void)setHasPreserveOriginalLocation:(bool)arg1;
- (void)setLocations:(id)arg1;
- (void)setPlaceTypeLimit:(int)arg1;
- (void)setPreserveOriginalLocation:(bool)arg1;
- (id)unknownFields;
- (void)writeTo:(id)arg1;

@end
