/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriActivation.framework/SiriActivation
 */

@interface SiriUILockStateTransport : NSObject <NSCopying, NSSecureCoding> {
    NSNumber * _transport;
}

@property (nonatomic, retain) NSNumber *transport;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (unsigned long long)SiriUILockState;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithSiriUILockState:(unsigned long long)arg1;
- (void)setTransport:(id)arg1;
- (id)transport;

@end
