//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber;

@interface CoreMLVersion : NSObject
{
    NSNumber *_frameworkVersionNumber;
}

+ (id)getInternalFrameworkVersion;
- (void).cxx_destruct;
@property(copy, nonatomic) NSNumber *frameworkVersionNumber; // @synthesize frameworkVersionNumber=_frameworkVersionNumber;
- (id)init;

@end

