/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/RunningBoard.framework/RunningBoard
 */

@interface RBPersonaManager : NSObject {
    NSMutableDictionary * _cachedPersonaIdentifiers;
    NSObject<OS_dispatch_queue> * _lockQueue;
    long long  _personalID;
}

- (void).cxx_destruct;
- (id)init;

@end
