/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriKitRuntime.framework/SiriKitRuntime
 */

@interface SiriKitRuntime.SiriKitEventSubject : _TtCs12_SwiftObject {
    void asyncSubscribersCancelDispatchGroup;
    void subject;
}

@end
