//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class _NSAsynchronousPreparation;
@protocol _NSAsynchronousPreparationInputParameters;

@protocol _NSAsynchronousPreparationDelegate <NSObject>
- (void)asynchronousPreparationDidChangePreparedResult:(_NSAsynchronousPreparation *)arg1;
- (id)asynchronousPreparation:(_NSAsynchronousPreparation *)arg1 prepareResultUsingParameters:(id <_NSAsynchronousPreparationInputParameters>)arg2;
@end

