//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSCell;

__attribute__((visibility("hidden")))
@interface _NSCellTrackingData : NSObject
{
    NSCell *_mouseCell;
    long long _mouseRow;
    long long _mouseCol;
    BOOL _cellNeedsDisplay;
}

- (void).cxx_destruct;
@property BOOL cellNeedsDisplay; // @synthesize cellNeedsDisplay=_cellNeedsDisplay;
@property(retain, nonatomic) NSCell *mouseCell; // @synthesize mouseCell=_mouseCell;
@property long long mouseCol; // @synthesize mouseCol=_mouseCol;
@property long long mouseRow; // @synthesize mouseRow=_mouseRow;

@end

