//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSAnimation.h>

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface _NSPathLocationAnimation : NSAnimation
{
    NSMutableArray *_originalWidths;
}

- (void)setCurrentProgress:(float)arg1;
- (long long)originalWidthsCount;
- (double)originalWidthForIndex:(long long)arg1;
- (void)addOriginalWidth:(double)arg1;
- (void)dealloc;

@end

