//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSAutoreleaseIdentifier, NSThread;

__attribute__((visibility("hidden")))
@interface NSAutoreleaseProxy : NSObject
{
    NSThread *_initialThread;
    NSAutoreleaseIdentifier *_identifier;
}

@property(readonly) NSAutoreleaseIdentifier *identifier; // @synthesize identifier=_identifier;
@property(readonly) NSThread *initialThread; // @synthesize initialThread=_initialThread;
- (void)dealloc;
- (id)initWithIdentifier:(id)arg1;

@end

