//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSDisplayLink1.h>

__attribute__((visibility("hidden")))
@interface NSScreenDisplayLink : NSDisplayLink1
{
    long long _screenNumber;
    CDUnknownBlockType _handler;
    struct __CFRunLoopTimer *_timer;
    struct os_unfair_lock_s _lock;
    unsigned long long _scheduleCount;
    unsigned long long _targetTime;
    unsigned int _paused:1;
    unsigned int _firing:1;
}

- (double)duration;
- (double)timestamp;
- (void)setPaused:(BOOL)arg1;
- (BOOL)isPaused;
- (BOOL)isValid;
- (void)invalidate;
- (void)removeFromRunLoop:(id)arg1 forMode:(id)arg2;
- (void)addToRunLoop:(id)arg1 forMode:(id)arg2;
- (void)_schedule;
- (void)_fire;
- (void)dealloc;
- (id)init;
- (id)initWithScreen:(id)arg1 handler:(CDUnknownBlockType)arg2;

@end

