//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <AppKit/NSCoding-Protocol.h>
#import <AppKit/NSCopying-Protocol.h>

@interface NSSliderAccessoryBehavior : NSObject <NSCoding, NSCopying>
{
}

+ (id)behaviorWithTarget:(id)arg1 action:(SEL)arg2;
+ (id)behaviorWithHandler:(CDUnknownBlockType)arg1;
+ (id)valueResetBehavior;
+ (id)valueStepBehavior;
+ (id)automaticBehavior;
- (BOOL)repeatsOnLongPressForAccessory:(id)arg1;
- (void)handleAction:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

