//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSLayoutManager;

@interface NSToolTipStringDrawingLayoutManager : NSObject
{
    NSDictionary *_wrappingAttributes;
    NSLayoutManager *_layoutManager;
}

+ (struct CGSize)sizeForDisplayingAttributedString:(id *)arg1;
+ (id)sharedToolTipStringDrawingLayoutManager;
@property(readonly, retain) NSDictionary *wrappingAttributes; // @synthesize wrappingAttributes=_wrappingAttributes;
- (void)dealloc;
- (struct CGSize)_sizeWithSize:(struct CGSize)arg1 attributedString:(id *)arg2;
- (id)_wrappingAttributes;

@end

