//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <HomeKit/HMAccessoryBrowserDelegate-Protocol.h>

@class HMAccessory, HMAccessoryBrowser;

@protocol HMAccessoryBrowserPrivateDelegate <HMAccessoryBrowserDelegate>

@optional
- (void)accessoryBrowser:(HMAccessoryBrowser *)arg1 didUpdateNewAccessory:(HMAccessory *)arg2;
@end

