//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MobileAsset/MAAsset.h>

@interface MAAsset (CFMorphunAssetsManager)
- (long long)morphunCompareByVersion:(id)arg1;
- (id)morphunModelDir;
- (id)morphunModelPath;
- (BOOL)isMorphunDownloading;
- (BOOL)isMorphunOnDisk;
- (BOOL)isMorphunInstalled;
- (id)morphunPath;
- (id)morphunContentVersion;
- (id)morphunMasteredVersion;
- (id)morphunLanguage;
- (id)morphunDescription;
@end

