/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MLCompute.framework/MLCompute
 */

@interface _MLCANEModelObject : NSObject {
    NSDictionary * _ANEFOptions;
    _ANEClient * _connection;
    NSDictionary * _graphPlist;
    _ANEModel * _model;
    unsigned int  _qos;
    _ANERequest * _request;
}

@property (nonatomic, readonly) NSDictionary *ANEFOptions;
@property (nonatomic, readonly) _ANEClient *connection;
@property (nonatomic, readonly) NSDictionary *graphPlist;
@property (nonatomic, readonly) _ANEModel *model;
@property (nonatomic, readonly) unsigned int qos;
@property (nonatomic, retain) _ANERequest *request;

+ (id)objectWithModel:(id)arg1 connection:(id)arg2 request:(id)arg3 options:(id)arg4 qos:(unsigned int)arg5 graphPlist:(id)arg6;

- (void).cxx_destruct;
- (id)ANEFOptions;
- (id)connection;
- (void)dealloc;
- (id)graphPlist;
- (id)initWithModel:(id)arg1 connection:(id)arg2 request:(id)arg3 options:(id)arg4 qos:(unsigned int)arg5 graphPlist:(id)arg6;
- (id)model;
- (unsigned int)qos;
- (id)request;
- (void)setRequest:(id)arg1;

@end
