//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface VCDispatchQueue : NSObject
{
    struct _opaque_pthread_mutex_t _lock;
    NSMutableArray *_rootQueues;
}

+ (id)defaultManager;
- (id)getCustomRootQueueWithPriority:(int)arg1 isFixedPriority:(BOOL)arg2;
- (void)dealloc;
- (id)init;

@end

