//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class NSString, NSTextField, NSView;
@protocol AKiCDPRecoveryKeyDelegate, MBSecondPartyHost;

@interface AKiCDPRecoveryKeyViewController : NSViewController
{
    BOOL _showErrorString;
    BOOL _recoveryKeyTextFieldEnabled;
    BOOL _noRecoveryKeyButtonVisible;
    BOOL _noRecoveryKeyButtonEnabled;
    NSTextField *_recoveryKeyTextField;
    NSView *_progressView;
    NSString *_recoveryKey;
    id <AKiCDPRecoveryKeyDelegate> _delegate;
    id <MBSecondPartyHost> _assistant;
}

- (void).cxx_destruct;
@property id <MBSecondPartyHost> assistant; // @synthesize assistant=_assistant;
@property id <AKiCDPRecoveryKeyDelegate> delegate; // @synthesize delegate=_delegate;
@property BOOL noRecoveryKeyButtonEnabled; // @synthesize noRecoveryKeyButtonEnabled=_noRecoveryKeyButtonEnabled;
@property BOOL noRecoveryKeyButtonVisible; // @synthesize noRecoveryKeyButtonVisible=_noRecoveryKeyButtonVisible;
@property BOOL recoveryKeyTextFieldEnabled; // @synthesize recoveryKeyTextFieldEnabled=_recoveryKeyTextFieldEnabled;
@property BOOL showErrorString; // @synthesize showErrorString=_showErrorString;
@property(retain) NSString *recoveryKey; // @synthesize recoveryKey=_recoveryKey;
@property(retain) NSView *progressView; // @synthesize progressView=_progressView;
@property(retain) NSTextField *recoveryKeyTextField; // @synthesize recoveryKeyTextField=_recoveryKeyTextField;
- (void)validateRecoveryKey;
- (void)noRecoveryKeyButtonPressed:(id)arg1;
- (void)recoveryTextFieldAction:(id)arg1;
- (void)controlTextDidChange:(id)arg1;
- (void)startRecoveryKeyFlow;
- (id)initWithDelegate:(id)arg1 assistant:(id)arg2;

@end

