//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class AKiCDPValidationDevice, NSArray, NSString;

@protocol AKiCDPValidationDelegate
@property(readonly) BOOL offerServerRecovery;
@property(readonly) BOOL offerRemoteApproval;
@property(readonly) NSArray *devices;
- (void)userCanceled;
- (void)triggerEscapeHatch;
- (void)cancelApproveFromAnotherDevice;
- (void)approveFromAnotherDevice;
- (void)validateDevice:(AKiCDPValidationDevice *)arg1 withSecret:(NSString *)arg2 completionHandler:(void (^)(BOOL, BOOL, BOOL, NSString *, NSString *))arg3;
@end

