//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <PhotosUICore/PXSectionedDataSourceManagerObserver-Protocol.h>

@class PXAssetsDataSourceManager;

@protocol PXAssetsDataSourceManagerObserver <PXSectionedDataSourceManagerObserver>

@optional
- (void)assetsDataSourceManagerDidFinishBackgroundFetching:(PXAssetsDataSourceManager *)arg1;
@end

