//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <PhotosUICore/NSObject-Protocol.h>

@class PXTilingLayout, PXTilingLayoutInvalidationContext;

@protocol PXTilingLayoutObserver <NSObject>
- (void)tilingLayout:(PXTilingLayout *)arg1 invalidatedWithContext:(PXTilingLayoutInvalidationContext *)arg2;
@end

