//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Catalyst/NSObject-Protocol.h>

@class CATTaskOperation, NSDictionary, NSString;

@protocol CATTaskOperationNotificationDelegate <NSObject>

@optional
- (void)taskOperation:(CATTaskOperation *)arg1 didPostNotificationWithName:(NSString *)arg2 userInfo:(NSDictionary *)arg3;
@end

