/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI.framework/NewsUI
 */

@interface NUNowPlayingViewController : UIViewController <NUNowPlayingBottomControlsDelegate, NUNowPlayingPlaybackControlsDelegate, NUNowPlayingPlaybackControlsLayoutSpecProvider, NUNowPlayingPlaybackScrubberDelegate, NUNowPlayingTitleViewLayoutSpecProvider> {
    NUNowPlayingArtworkView * _artworkView;
    NUNowPlayingBottomControls * _bottomControls;
    UIView * _contentView;
    <NUNowPlayingViewControllerDelegate> * _delegate;
    UIButton * _dismissButton;
    _UIGrabber * _grabberView;
    NUNowPlayingPlaybackControls * _playbackControls;
    NUNowPlayingPlaybackScrubber * _playbackScrubber;
    NUNowPlayingTitleView * _titleView;
    NUNowPlayingVolumeControl * _volumeControl;
}

@property (nonatomic, retain) NUNowPlayingArtworkView *artworkView;
@property (nonatomic, retain) NUNowPlayingBottomControls *bottomControls;
@property (nonatomic, retain) UIView *contentView;
@property (nonatomic) <NUNowPlayingViewControllerDelegate> *delegate;
@property (nonatomic, retain) UIButton *dismissButton;
@property (nonatomic, retain) _UIGrabber *grabberView;
@property (nonatomic, retain) NUNowPlayingPlaybackControls *playbackControls;
@property (nonatomic, retain) NUNowPlayingPlaybackScrubber *playbackScrubber;
@property (nonatomic, readonly) double publisherLogoHeight;
@property (nonatomic, retain) NUNowPlayingTitleView *titleView;
@property (nonatomic, retain) NUNowPlayingVolumeControl *volumeControl;

- (void).cxx_destruct;
- (void)applicationWillEnterForeground;
- (struct CGSize { double x1; double x2; })artworkSizeForViewWidth:(double)arg1;
- (void)artworkTapped:(id)arg1;
- (id)artworkView;
- (id)bottomControls;
- (id)contentView;
- (id)contextMenuInteraction:(id)arg1 configurationForMenuAtLocation:(struct CGPoint { double x1; double x2; })arg2;
- (id)delegate;
- (id)dismissButton;
- (void)dismissButtonTapped:(id)arg1;
- (id)grabberView;
- (id)init;
- (void)loadView;
- (double)nextTrackAndRewindButtonPointSize;
- (void)nowPlayingBottomControlsDidTapEllipsis:(id)arg1;
- (void)nowPlayingBottomControlsDidTapPlaybackSpeed:(id)arg1;
- (void)nowPlayingPlaybackControlsDidTapNextTrack:(id)arg1;
- (void)nowPlayingPlaybackControlsDidTapPause:(id)arg1;
- (void)nowPlayingPlaybackControlsDidTapPlay:(id)arg1;
- (void)nowPlayingPlaybackControlsDidTapRewind:(id)arg1;
- (double)playPausePointSize;
- (id)playbackControls;
- (id)playbackScrubber;
- (double)publisherLogoBottomMargin;
- (double)publisherLogoHeight;
- (double)publisherLogoHeight;
- (void)seekToPosition:(double)arg1;
- (void)setArtwork:(id)arg1;
- (void)setArtwork:(id)arg1 backgroundImage:(id)arg2;
- (void)setArtworkView:(id)arg1;
- (void)setBottomControls:(id)arg1;
- (void)setContentView:(id)arg1;
- (void)setCurrentTime:(double)arg1 duration:(double)arg2 animated:(bool)arg3;
- (void)setDelegate:(id)arg1;
- (void)setDismissButton:(id)arg1;
- (void)setGrabberView:(id)arg1;
- (void)setIsPlaying:(bool)arg1 waiting:(bool)arg2;
- (void)setNextTrackButtonEnabled:(bool)arg1;
- (void)setPlaybackControls:(id)arg1;
- (void)setPlaybackScrubber:(id)arg1;
- (void)setPublisherImage:(id)arg1 fallbackName:(id)arg2;
- (void)setRate:(double)arg1;
- (void)setTitle:(id)arg1;
- (void)setTitleView:(id)arg1;
- (void)setVolumeControl:(id)arg1;
- (double)titleLabelFontSize;
- (id)titleView;
- (void)titleViewTapped:(id)arg1;
- (void)viewDidDisappear:(bool)arg1;
- (void)viewDidLoad;
- (void)viewWillDisappear:(bool)arg1;
- (void)viewWillLayoutSubviews;
- (id)volumeControl;

@end
