//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GameplayKit/GKAgent.h>

@class MISSING_TYPE;

@interface GKAgent3D : GKAgent
{
}

+ (BOOL)supportsSecureCoding;
- (void)applyBrakingForce:(float)arg1 deltaTime:(double)arg2;
- (void)applySteeringForce:(double)arg1 deltaTime: /* Error: Ran out of types for this method. */;
- (void)updateWithDeltaTime:(double)arg1;
@property(nonatomic) CDStruct_d80e62f2 rotation;
@property(nonatomic) BOOL rightHanded;
@property(readonly, nonatomic) MISSING_TYPE *velocity;
@property(nonatomic) MISSING_TYPE *position;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

