//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SiriVOX/SVXClientServiceConsuming-Protocol.h>
#import <SiriVOX/SVXClientSessionStateServicing-Protocol.h>

@class NSString;
@protocol SVXClientServiceProviding, SVXClientSessionStateServiceDelegate, SVXPerforming;

@interface SVXClientSessionStateService : NSObject <SVXClientServiceConsuming, SVXClientSessionStateServicing>
{
    id <SVXPerforming> _performer;
    id <SVXClientServiceProviding> _clientServiceProvider;
    long long _currentState;
    id <SVXClientSessionStateServiceDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <SVXClientSessionStateServiceDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) long long currentState; // @synthesize currentState=_currentState;
- (void)_setCurrentState:(long long)arg1;
- (void)fetchStateWithCompletion:(CDUnknownBlockType)arg1;
- (void)clientServiceDidChange;
- (id)initWithClientServiceProvider:(id)arg1 performer:(id)arg2;
- (void)handleDidChangeSessionStateFrom:(long long)arg1 to:(long long)arg2;
- (void)handleWillChangeSessionStateFrom:(long long)arg1 to:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

