//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MultitouchDeviceObserver : NSObject
{
}

+ (id)sharedObserver;
@property(readonly) long long attachedDevices; // @dynamic attachedDevices;
- (struct __CFDictionary *)_createHapticTrackpadMatchingDictionary;

@end

