/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PegasusAPI.framework/PegasusAPI
 */

@interface _TtCV10PegasusAPI21Useragentpb_UserAgentP33_3526F11A9FBAF1EBFEEA0893EF41119B13_StorageClass : _TtCs12_SwiftObject {
    void _client;
    void _clientVersion;
    void _device;
    void _generation;
    void _hardware;
    void _isClientReportedInternal;
    void _isClientReportedSeed;
    void _isDebug;
    void _osVersion;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  _parsedOsVersion;
    void _productVersion;
    void _screenSize;
    void _skuregion;
    void _subGeneration;
    void _value;
}

@end
