/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriOntology.framework/SiriOntology
 */

@interface _TtCV12SiriOntology35Siri_Nl_Core_Protocol_UserContinuedP33_C00432D0398FDC59A6695A04F384D31813_StorageClass : _TtCs12_SwiftObject {
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  _step;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  _taskID;
}

@end
