//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol MCPlugTiming
@property(nonatomic) double numberOfLoops;
@property(readonly, nonatomic) double fullDuration;
@property(nonatomic) double phaseOutDuration;
@property(nonatomic) double loopDuration;
@property(nonatomic) double phaseInDuration;
@end

