//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SafariCore/WBSPair.h>

#import <SafariCore/NSSecureCoding-Protocol.h>

@interface WBSSandboxExtensionDataPair : WBSPair <NSSecureCoding>
{
}

+ (BOOL)supportsSecureCoding;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithToken:(id)arg1 permissions:(id)arg2;
- (id)initWithFirst:(id)arg1 second:(id)arg2;

@end

