//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSData.h>

@interface NSMutableData : NSData
{
}


// Remaining properties
@property unsigned long long length; // @dynamic length;
@property(readonly) void *mutableBytes; // @dynamic mutableBytes;
@end

