//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSControl.h"

@class NSImageView;

@interface GKRatingControl : NSControl
{
    double _value;
    NSImageView *_dotsImageView;
    NSImageView *_starsImageView;
    double _trackingValue;
    struct CGPoint _lastLocation;
}

@property(nonatomic) double trackingValue; // @synthesize trackingValue=_trackingValue;
@property(nonatomic) struct CGPoint lastLocation; // @synthesize lastLocation=_lastLocation;
@property(retain, nonatomic) NSImageView *starsImageView; // @synthesize starsImageView=_starsImageView;
@property(retain, nonatomic) NSImageView *dotsImageView; // @synthesize dotsImageView=_dotsImageView;
@property(nonatomic) double value; // @synthesize value=_value;
- (void)setEnabled:(BOOL)arg1;
- (void)layoutSubviews;
- (struct CGSize)intrinsicContentSize;
- (void)setupImages;
- (void)_commonInit;
- (void)awakeFromNib;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

