//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ScriptingBridge/SBObject.h>

@class NSDate;

@interface _AMAddressBookEntry : SBObject
{
}

- (id)removeFrom:(id)arg1;
- (id)addTo:(id)arg1;
- (void)moveTo:(id)arg1;
- (void)duplicateTo:(id)arg1 withProperties:(id)arg2;
- (void)delete;
- (void)printWithProperties:(id)arg1 printDialog:(BOOL)arg2;
- (void)saveIn:(id)arg1 as:(id)arg2;
- (void)closeSaving:(int)arg1 savingIn:(id)arg2;
@property BOOL selected;
- (id)id;
@property(readonly, copy) NSDate *creationDate;
@property(readonly, copy) NSDate *modificationDate;

@end

