//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Automator/_AMFinderProcess.h>

@class _AMFinderApplicationFile;

@interface _AMFinderApplicationProcess : _AMFinderProcess
{
}

@property(readonly, copy) _AMFinderApplicationFile *applicationFile;

@end

