//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ScriptingBridge/SBObject.h>

@class NSColor, NSNumber, NSString;

@interface _AMiCalText : SBObject
{
}

- (void)show;
- (void)GetURL;
- (void)saveIn:(id)arg1 as:(id)arg2;
- (void)moveTo:(id)arg1;
- (BOOL)exists;
- (void)duplicateTo:(id)arg1 withProperties:(id)arg2;
- (void)delete;
- (void)closeSaving:(int)arg1 savingIn:(id)arg2;
@property(copy) NSNumber *size;
@property(copy) NSString *font;
@property(copy) NSColor *color;
- (id)attachments;
- (id)attributeRuns;
- (id)characters;
- (id)words;
- (id)paragraphs;

@end

