//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Automator/_AMKeynote5Text.h>

@class NSString;

@interface _AMKeynote5Attachment : _AMKeynote5Text
{
}

@property(copy) NSString *fileName;

@end

