//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Automator/_AMSystemEventsDiskItem.h>

@interface _AMSystemEventsFolder : _AMSystemEventsDiskItem
{
}

- (id)folders;
- (id)filePackages;
- (id)files;
- (id)diskItems;
- (id)aliases;

@end

