//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;
@protocol OS_dispatch_queue;

@interface KHDBTrigger : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    NSMutableDictionary *_entries;
    int _firing;
}

- (void)fire;
- (void)deregisterBlock:(id)arg1;
- (void)registerBlock:(CDUnknownBlockType)arg1 onQueue:(id)arg2 withKey:(id)arg3;
- (void)dealloc;
- (id)init;

@end

