//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIFoundation/NSGlyphGenerator.h>

@interface NSConcreteGlyphGenerator : NSGlyphGenerator
{
    char *bidiTypes;
    char *bidiLevels;
}

+ (id)sharedGlyphGenerator;
- (void)generateGlyphsForGlyphStorage:(id)arg1 desiredNumberOfCharacters:(unsigned long long)arg2 glyphIndex:(unsigned long long *)arg3 characterIndex:(unsigned long long *)arg4;

@end

