/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ShazamKit.framework/ShazamKit
 */

@interface SHLocalization : NSObject

+ (id)localizedStringForKey:(id)arg1;
+ (id)shFrameworkBundle;

@end
