/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VFX.framework/VFX
 */

@interface VFXCore.RenderBuckets : _TtCs12_SwiftObject {
    void materialTransparentBuckets;
    void opaqueDrawList;
    void renderContext;
}

@end
