/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/FileProvider.framework/FileProvider
 */

@interface _NSFileProviderEmptyItemVersion : NSFileProviderItemVersion

+ (id)emptyVersion;
+ (bool)supportsSecureCoding;

- (id)contentVersion;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)metadataVersion;

@end
