/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDCameraResidentMessageHandler : HMFObject <HMFLogging> {
    HMDAccessory * _accessory;
    HMFUnfairLock * _lock;
    NSString * _logIdentifier;
    NSMutableDictionary * _messageContextsBySessionID;
    HMDMessageDispatcher * _messageDispatcher;
}

@property (readonly) HMDAccessory *accessory;
@property (readonly) bool companionIsResident;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) HMFUnfairLock *lock;
@property (readonly, copy) NSString *logIdentifier;
@property (readonly, copy) NSMutableDictionary *messageContextsBySessionID;
@property (retain) HMDMessageDispatcher *messageDispatcher;
@property (readonly) HMDDevice *residentDeviceForCamera;
@property (readonly) Class superclass;

+ (id)logCategory;

- (void).cxx_destruct;
- (id)accessory;
- (bool)companionIsResident;
- (id)dequeueMessageContextForCameraSessionID:(id)arg1;
- (void)enqueueMessageContext:(id)arg1 forCameraSessionID:(id)arg2;
- (id)initWithAccessory:(id)arg1 logID:(id)arg2;
- (id)lock;
- (id)logIdentifier;
- (id)messageContextsBySessionID;
- (id)messageDispatcher;
- (id)residentDeviceForCamera;
- (void)sendMessageForCameraWithSessionID:(id)arg1;
- (void)sendMessageWithName:(id)arg1 cameraSessionID:(id)arg2 payload:(id)arg3 target:(id)arg4 device:(id)arg5 responseQueue:(id)arg6 responseHandler:(id /* block */)arg7;
- (void)sendMessageWithName:(id)arg1 cameraSessionID:(id)arg2 payload:(id)arg3 target:(id)arg4 responseQueue:(id)arg5 responseHandler:(id /* block */)arg6;
- (void)sendRemoteMessageWithName:(id)arg1 cameraSessionID:(id)arg2 payload:(id)arg3 target:(id)arg4 device:(id)arg5 responseQueue:(id)arg6 responseHandler:(id /* block */)arg7;
- (void)setMessageDispatcher:(id)arg1;

@end
