/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsPersonalization.framework/NewsPersonalization
 */

@interface NXServiceAssembly : NSObject <NFAssembly>

- (id)init;
- (void)loadInRegistry:(id)arg1;

@end
